from __future__ import annotations

from ..manager import ProviderManager
from ..types import CostTier, ModelInfo, ProviderProfile


def register_profile(manager: ProviderManager) -> None:

    manager.register(
        ProviderProfile(
            name="anthropic",
            display_name="Anthropic",
            models=[
                ModelInfo(
                    "claude-fable-5",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1000000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "claude-opus-4-8",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "claude-opus-4-7",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "claude-opus-4-6",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "claude-sonnet-4-6",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "claude-haiku-4-5",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.LOW,
                ),
                ModelInfo(
                    "claude-sonnet-4",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "claude-sonnet-4-5",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "claude-opus-4",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "claude-opus-4-5",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
            ],
            api_key_env="ANTHROPIC_API_KEY",
            max_context_tokens=1000000,
            supports_streaming=True,
            supports_vision=True,
            priority=9,
            cost_tier=CostTier.HIGH,
            docs_url="https://docs.anthropic.com/en/docs/about-claude/models",
        )
    )
