from __future__ import annotations
from ..types import ProviderProfile, ModelInfo, CostTier


def register_profile(manager) -> None:
    # Adjust indentation

    # ── Google Gemini ──────────────────────────────────────────────
    manager.register(
        ProviderProfile(
            name="gemini",
            display_name="Google Gemini",
            models=[
                ModelInfo(
                    "gemini-3.5-pro",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=2000000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "gemini-3.5-flash",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1000000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "gemini-3.1-pro-preview",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "gemini-3.1-pro",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=2000000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "gemini-3.1-flash",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "gemini-3.1-flash-lite",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.LOW,
                ),
                ModelInfo(
                    "gemini-3-flash-preview",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "gemini-3.0-pro",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "gemini-3.0-flash",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.LOW,
                ),
                ModelInfo(
                    "gemini-2.5-pro",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "gemini-2.5-flash",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.LOW,
                ),
                ModelInfo(
                    "gemini-2.5-flash-lite",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.FREE,
                ),
                ModelInfo(
                    "gemini-2.0-flash",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1048576,
                    cost_tier=CostTier.FREE,
                ),
            ],
            api_key_env="GEMINI_API_KEY",
            max_context_tokens=2000000,
            supports_streaming=True,
            supports_vision=True,
            priority=9,
            cost_tier=CostTier.LOW,
            docs_url="https://ai.google.dev/gemini-api/docs/models",
        )
    )
