from __future__ import annotations
from ..types import ProviderProfile, ModelInfo, CostTier
from ..manager import ProviderManager


def register_profile(manager: ProviderManager) -> None:
    # Adjust indentation

    # ── OpenAI ──────────────────────────────────────────────────────
    manager.register(
        ProviderProfile(
            name="openai",
            display_name="OpenAI",
            models=[
                ModelInfo(
                    "gpt-5.5",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1000000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "gpt-5.5-pro",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=1000000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "gpt-5.4",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=272000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "gpt-5.4-pro",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1050000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "gpt-5.4-mini",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=400000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "gpt-5.4-nano",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=400000,
                    cost_tier=CostTier.LOW,
                ),
                ModelInfo(
                    "gpt-5.3-codex",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=400000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "gpt-5.2",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=400000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "gpt-4.1",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1000000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "gpt-4.1-mini",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1000000,
                    cost_tier=CostTier.LOW,
                ),
                ModelInfo(
                    "gpt-4.1-nano",
                    supports_vision=True,
                    supports_structured_output=True,
                    context_window=1000000,
                    cost_tier=CostTier.LOW,
                ),
                ModelInfo(
                    "o4-mini",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=200000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "o4-mini-deep-research",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "o3",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "o3-mini",
                    supports_vision=False,
                    supports_structured_output=False,
                    context_window=200000,
                    cost_tier=CostTier.MEDIUM,
                ),
                ModelInfo(
                    "o3-pro",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "o3-deep-research",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "o1",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
                ModelInfo(
                    "o1-pro",
                    supports_vision=True,
                    supports_structured_output=False,
                    context_window=200000,
                    cost_tier=CostTier.HIGH,
                ),
            ],
            api_key_env="OPENAI_API_KEY",
            max_context_tokens=1000000,
            supports_streaming=True,
            supports_vision=True,
            priority=10,
            cost_tier=CostTier.HIGH,
            docs_url="https://platform.openai.com/docs/models",
        )
    )
