#!/usr/bin/env python3
"""Comprehensive Recon NLP evaluation — 440 commands, direct + natlang, basic->advanced->complex."""

import sys

sys.stdout.reconfigure(encoding="utf-8")

from siyarix import RegistryPlanner

AVAILABLE_TOOLS = [
    "nmap",
    "masscan",
    "rustscan",
    "naabu",
    "gobuster",
    "ffuf",
    "dirb",
    "dirsearch",
    "whatweb",
    "wappalyzer",
    "builtwith",
    "nuclei",
    "nikto",
    "wapiti",
    "skipfish",
    "hydra",
    "medusa",
    "ncrack",
    "patator",
    "subfinder",
    "amass",
    "sublist3r",
    "assetfinder",
    "curl",
    "wget",
    "httpie",
    "dig",
    "nslookup",
    "host",
    "aircrack-ng",
    "hashcat",
    "john",
    "sqlmap",
    "jSQL",
    "sqlninja",
    "whois",
    "openssl",
    "eyewitness",
    "tracert",
    "traceroute",
    "responder",
    "impacket",
    "impacket-secretsdump",
    "impacket-GetUserSPNs",
    "impacket-GetNPUsers",
    "bloodhound-python",
    "searchsploit",
    "shodan",
    "censys",
    "theHarvester",
    "gau",
    "waybackurls",
    "httpx",
    "katana",
    "gospider",
    "uncover",
    "subjack",
    "trufflehog",
    "gitleaks",
    "sherlock",
    "holehe",
    "maigret",
    "dnsx",
    "massdns",
    "puredns",
    "arjun",
    "paramspider",
    "cloud_enum",
    "scoutsuite",
    "prowler",
    "interactsh",
    "testssl.sh",
    "ssllabs-scan",
    "bluetoothctl",
    "crackmapexec",
    "netexec",
    "enum4linux",
    "wpscan",
]


def check_plan(planner, goal, expected_tools, min_steps=1, max_steps=None):
    plan = planner.decompose_goal(goal)
    actual_tools = [s.tool for s in plan.steps]
    step_count = len(plan.steps)
    if step_count < min_steps:
        return False, f"step_count {step_count} < min_steps {min_steps}, tools={actual_tools}"
    if max_steps and step_count > max_steps:
        return False, f"step_count {step_count} > max_steps {max_steps}, tools={actual_tools}"
    for et in expected_tools:
        if et not in actual_tools:
            return False, f"expected {et!r} not in {actual_tools}"
    return True, f"OK steps={step_count} tools={actual_tools}"


RECON_COMMANDS = [
    # ===== SECTION 1: BASIC NETWORK RECON (22) =====
    ("nmap scan on 10.0.0.1", ["nmap"], 1, 1),
    ("port scan on 10.0.0.1", ["nmap", "nmap", "dig", "whois", "masscan"], 5, 5),
    ("full port scan on 10.0.0.1", ["nmap", "nmap", "dig", "whois", "masscan"], 5, 5),
    ("quick scan on 10.0.0.1", ["nmap"], 1, 1),
    ("tcp scan on 10.0.0.1", ["nmap", "nmap", "dig", "whois", "masscan"], 5, 5),
    ("udp scan on 10.0.0.1", ["nmap"], 1, 1),
    ("stealth scan on 10.0.0.1", ["nmap"], 1, 1),
    ("ping sweep on 10.0.0.0/24", ["nmap"], 1, 1),
    ("host discovery on 192.168.1.0/24", ["nmap"], 1, 1),
    ("live hosts scan on 172.16.0.0/24", ["nmap"], 1, 1),
    ("find up hosts on 10.0.0.0/24", ["nmap"], 1, 1),
    ("Check what ports are open on 10.0.0.1", ["nmap"], 1, 1),
    ("service version scan on 10.0.0.1", ["nmap"], 1, 1),
    ("aggressive scan on 10.0.0.1 all ports", ["nmap"], 1, 1),
    ("fast port scan on 10.0.0.1 top 1000", ["nmap", "nmap", "dig", "whois", "masscan"], 5, 5),
    ("masscan full sweep on 10.0.0.0/16", ["masscan"], 1, 1),
    ("rustscan on 10.0.0.1", ["rustscan"], 1, 1),
    ("naabu fast scan on 10.0.0.1", ["naabu"], 1, 1),
    ("traceroute to example.com", ["tracert"], 1, 1),
    ("tracert to 8.8.8.8", ["tracert"], 1, 1),
    (
        "Can you run a network scan on 10.0.0.1 and tell me what services are running?",
        ["nmap", "nmap", "dig", "whois", "masscan"],
        5,
        5,
    ),
    ("I need to discover all live hosts on the 10.0.0.0/24 subnet", ["nmap"], 1, 1),
    # ===== SECTION 2: ADVANCED NETWORK RECON (16) =====
    ("full tcp scan on 10.0.0.1 all ports", ["nmap", "nmap", "dig", "whois", "masscan"], 5, 5),
    ("infrastructure scan on 10.0.0.1", ["nmap", "nmap", "dig", "whois", "masscan"], 5, 5),
    ("open ports check on 10.0.0.1", ["nmap", "nmap", "dig", "whois", "masscan"], 5, 5),
    ("nmap os detection on 10.0.0.1", ["nmap"], 1, 1),
    ("ipmi recon on 10.0.0.1", ["nmap"], 1, 1),
    ("snmp enumeration on 10.0.0.1", ["nmap"], 1, 1),
    ("smtp server enum on mail.example.com", ["nmap"], 1, 1),
    ("imap enumeration on 10.0.0.1", ["nmap"], 1, 1),
    ("tcp port sweep 10.0.0.0/24", ["nmap"], 1, 1),
    (
        "network mapping on 10.0.0.0/24",
        ["curl", "whatweb", "nuclei", "gobuster", "dig", "subfinder", "whois", "nmap", "masscan"],
        9,
        9,
    ),
    ("scan for up hosts and open services on 10.0.0.0/24", ["nmap"], 1, 1),
    (
        "Perform a full infrastructure scan of 10.0.0.1 including OS detection",
        ["nmap", "nmap", "dig", "whois", "masscan"],
        5,
        5,
    ),
    ("I need to do SNMP recon on the target 10.0.0.1 to enumerate network devices", ["nmap"], 1, 1),
    ("Run IPMI reconnaissance on 10.0.0.1 to check for BMC vulnerabilities", ["nmap"], 1, 1),
    (
        "Do a masscan of the entire 10.0.0.0/16 range to find all responsive hosts",
        ["masscan"],
        1,
        1,
    ),
    (
        "Network scan for SMTP, IMAP, and POP3 services on mail.example.com",
        ["nmap", "nmap", "dig", "whois", "masscan"],
        5,
        5,
    ),
    # ===== SECTION 3: DNS RECON (28) =====
    ("dns enumeration on example.com", ["dig", "subfinder", "amass", "whois"], 4, 4),
    ("dns record check for example.com", ["dig", "subfinder", "amass", "whois"], 4, 4),
    ("mx record lookup for example.com", ["dig", "subfinder", "amass", "whois"], 4, 4),
    ("dns resolution for example.com", ["dig", "subfinder", "amass", "whois"], 4, 4),
    ("nameserver lookup for example.com", ["dig", "subfinder", "amass", "whois"], 4, 4),
    ("dns zone transfer on example.com", ["dig"], 1, 1),
    ("axfr query for example.com", ["dig"], 1, 1),
    ("dns a record check for example.com", ["dig"], 1, 1),
    ("dns txt record enumeration for example.com", ["dig"], 1, 1),
    ("dns cname lookup for example.com", ["dig"], 1, 1),
    ("reverse dns lookup on 8.8.8.8", ["dig"], 1, 1),
    ("dns ptr record for 8.8.8.8", ["dig"], 1, 1),
    ("dns soa record for example.com", ["dig"], 1, 1),
    ("aaaa record check for example.com", ["dig"], 1, 1),
    ("dnssec check for example.com", ["dig"], 1, 1),
    ("spf record lookup for example.com", ["dig"], 1, 1),
    ("dmarc record check for example.com", ["dig"], 1, 1),
    ("dns cache snooping on 8.8.8.8", ["dig"], 1, 1),
    ("dnsx query on example.com", ["dnsx"], 1, 1),
    ("massdns on example.com with resolvers", ["massdns"], 1, 1),
    ("puredns resolve for example.com", ["puredns"], 1, 1),
    ("dns probe with dnsx on example.com", ["dnsx"], 1, 1),
    ("massdns brute force subdomains on example.com", ["massdns"], 1, 1),
    ("puredns wildcard filter for example.com", ["puredns"], 1, 1),
    ("dnsx a record query for example.com", ["dnsx"], 1, 1),
    ("bulk dns resolution with dnsx for example.com", ["dnsx"], 1, 1),
    (
        "Look up the MX, SPF, and DMARC records for example.com to understand email security",
        ["dig"],
        1,
        1,
    ),
    (
        "Do a full DNS reconnaissance on example.com including all record types and zone transfer attempt",
        ["dig", "subfinder", "amass", "whois"],
        4,
        4,
    ),
    # ===== SECTION 4: WHOIS & DOMAIN OSINT (20) =====
    ("whois lookup for example.com", ["whois"], 1, 1),
    ("domain whois on example.com", ["whois"], 1, 1),
    ("whois registration for example.com", ["whois"], 1, 1),
    ("reverse whois for example.com", ["whois"], 1, 1),
    ("asn lookup for 8.8.8.8", ["whois"], 1, 1),
    ("asn recon on AS15169", ["whois"], 1, 1),
    ("ip whois for 8.8.8.8", ["whois"], 1, 1),
    ("domain registration check example.com", ["whois"], 1, 1),
    ("whois domain ownership for example.com", ["whois"], 1, 1),
    ("rdap lookup for 8.8.8.8", ["whois"], 1, 1),
    ("registrar information for example.com", ["whois"], 1, 1),
    ("domain registration info for example.com", ["whois"], 1, 1),
    ("whois ip block ownership for 8.8.8.0/24", ["whois"], 1, 1),
    ("Find out who owns the domain example.com and get registrar details", ["whois"], 1, 1),
    ("I need to know what ASN owns the IP 8.8.8.8 and who its ISP is", ["whois"], 1, 1),
    (
        "Do a reverse WHOIS lookup on example.com to find other domains owned by the same person",
        ["whois"],
        1,
        1,
    ),
    (
        "Check domain registration expiry for example.com and look up registrar info",
        ["whois"],
        1,
        1,
    ),
    ("RDAP lookup on 8.8.8.8 to get the latest RIR data", ["whois"], 1, 1),
    ("Who owns this IP? Do a full whois investigation on 8.8.8.8", ["whois"], 1, 1),
    ("Look up the AS15169 ownership and find out what organization it belongs to", ["whois"], 1, 1),
    # ===== SECTION 5: SUBDOMAIN ENUMERATION (22) =====
    (
        "subdomain enumeration on example.com",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    (
        "subdomain discovery for example.com",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    ("amass subdomain brute on example.com", ["amass"], 1, 1),
    ("amass intel on example.com", ["amass"], 1, 1),
    ("amass enum for example.com", ["amass"], 1, 1),
    ("subfinder passive enum on example.com", ["subfinder"], 1, 1),
    ("sublist3r subdomain search for example.com", ["sublist3r"], 1, 1),
    ("assetfinder subdomain discovery for example.com", ["assetfinder"], 1, 1),
    (
        "passive subdomain enum on example.com",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    (
        "dns brute force subdomain on example.com",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    ("subdomain takeover check on example.com", ["subjack"], 1, 1),
    ("check subdomain takeover on example.com", ["subjack"], 1, 1),
    (
        "Find all subdomains of example.com using passive sources and brute force",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    (
        "Use subfinder and amass to enumerate subdomains for example.com",
        ["amass", "subfinder"],
        2,
        2,
    ),
    (
        "I need a comprehensive subdomain discovery on example.com including passive and active techniques",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    ("Check if any subdomains of example.com are vulnerable to takeover", ["subjack"], 1, 1),
    ("Run sublist3r to find subdomains for example.com", ["sublist3r"], 1, 1),
    ("Enumerate all subdomains passively using subfinder on example.com", ["subfinder"], 1, 1),
    ("Do an aggressive subdomain brute force with amass on example.com", ["amass"], 1, 1),
    (
        "Use assetfinder to find related domains and subdomains for example.com",
        ["assetfinder"],
        1,
        1,
    ),
    (
        "Enumerate subdomains for example.com then check which are alive",
        ["subfinder", "httpx"],
        2,
        2,
    ),
    ("subdomain brute force on example.com with amass and then httpx", ["amass", "httpx"], 2, 2),
    # ===== SECTION 6: WEB RECON - HEADERS & TECH (22) =====
    ("check headers of https://example.com", ["curl"], 1, 1),
    ("find tech stack on example.com", ["whatweb"], 1, 1),
    ("web technology fingerprint on example.com", ["whatweb"], 1, 1),
    ("tech stack detection on example.com", ["whatweb"], 1, 1),
    ("cms detection on https://example.com", ["whatweb"], 1, 1),
    ("wordpress scan on https://example.com", ["wpscan"], 1, 1),
    ("check http headers on https://example.com", ["curl", "openssl"], 2, 2),
    ("cors check on https://example.com", ["curl", "curl"], 2, 2),
    ("cookie analysis on https://example.com", ["curl"], 1, 1),
    ("redirect chain for https://example.com", ["curl"], 1, 1),
    ("clickjacking test on https://example.com", ["curl"], 1, 1),
    ("api endpoint check on https://example.com", ["curl"], 1, 1),
    ("check for exposed .git on https://example.com", ["curl"], 1, 1),
    ("joomla detection on https://example.com", ["whatweb"], 1, 1),
    ("drupal scan on https://example.com", ["whatweb"], 1, 1),
    ("nginx info on https://example.com", ["whatweb"], 1, 1),
    ("apache version check on https://example.com", ["whatweb"], 1, 1),
    ("iis fingerprint on https://example.com", ["whatweb"], 1, 1),
    ("tomcat manager check on https://example.com", ["whatweb"], 1, 1),
    (
        "What web server and technologies is example.com running? Check headers and tech stack",
        ["whatweb"],
        1,
        1,
    ),
    ("Check if example.com is running WordPress and what version", ["wpscan"], 1, 1),
    (
        "Inspect the HTTP security headers on https://example.com for missing protections",
        ["curl", "openssl"],
        2,
        2,
    ),
    # ===== SECTION 7: WEB RECON - DIRECTORY & FUZZING (16) =====
    ("enumerate directories on https://example.com", ["gobuster"], 1, 1),
    ("fuzz endpoints on https://example.com", ["ffuf"], 1, 1),
    ("directory busting on https://example.com", ["gobuster"], 1, 1),
    ("fuzz with ffuf on https://example.com/FUZZ", ["ffuf"], 1, 1),
    ("dirb scan on https://example.com", ["dirb"], 1, 1),
    ("dirsearch on https://example.com", ["dirsearch"], 1, 1),
    ("exposed panel scan on https://example.com", ["nuclei"], 1, 1),
    ("Find hidden directories and files on https://example.com using gobuster", ["gobuster"], 1, 1),
    ("Fuzz the https://example.com web app for hidden endpoints with ffuf", ["ffuf"], 1, 1),
    (
        "I want to brute force directories on https://example.com with a wordlist",
        ["nmap", "hydra", "hashcat"],
        3,
        3,
    ),
    ("Use dirsearch to find hidden paths on https://example.com", ["dirsearch"], 1, 1),
    ("Scan https://example.com for exposed admin panels and login pages", ["nuclei"], 1, 1),
    ("Run dirb on https://example.com to find common web directories", ["dirb"], 1, 1),
    ("Content discovery on https://example.com - find all accessible paths", ["gobuster"], 1, 1),
    ("Discover all endpoints and hidden files on https://example.com", ["gobuster"], 1, 1),
    (
        "Run a directory brute force and then check found paths for vulnerabilities",
        ["gobuster", "nuclei"],
        2,
        2,
    ),
    # ===== SECTION 8: SSL/TLS RECON (20) =====
    ("ssl check on https://example.com", ["openssl", "nmap", "nmap"], 3, 3),
    ("tls cipher scan on example.com", ["openssl", "nmap", "nmap"], 3, 3),
    ("certificate info for https://example.com", ["openssl"], 1, 1),
    ("full ssl audit on https://example.com", ["openssl", "nmap", "nmap"], 3, 3),
    ("tls cipher suite check on example.com", ["openssl", "nmap", "nmap"], 3, 3),
    ("heartbleed check on https://example.com", ["nmap"], 1, 1),
    ("ssl certificate chain validation for example.com", ["openssl", "nmap", "nmap"], 3, 3),
    ("ssl labs scan for example.com", ["ssllabs-scan"], 1, 1),
    ("testssl full check on example.com", ["testssl.sh"], 1, 1),
    ("ssl cipher enum on example.com:443", ["openssl", "nmap", "nmap"], 3, 3),
    ("ssllabs api scan for example.com", ["ssllabs-scan"], 1, 1),
    ("testssl audit on example.com", ["testssl.sh"], 1, 1),
    ("ssl tls security assessment on example.com", ["openssl", "nmap", "nmap"], 3, 3),
    (
        "Run a comprehensive SSL/TLS audit on example.com with cipher enumeration",
        ["openssl", "nmap", "nmap"],
        3,
        3,
    ),
    ("Check if example.com is vulnerable to Heartbleed", ["nmap"], 1, 1),
    (
        "Use SSLLabs to analyze example.com certificate and SSL configuration",
        ["ssllabs-scan"],
        1,
        1,
    ),
    (
        "Do a full testssl.sh assessment on example.com for TLS vulnerabilities",
        ["testssl.sh"],
        1,
        1,
    ),
    (
        "Validate the SSL certificate chain for https://example.com and check ciphers",
        ["openssl", "nmap", "nmap"],
        3,
        3,
    ),
    (
        "I need a detailed SSL report for example.com including weak cipher detection",
        ["openssl", "nmap", "nmap"],
        3,
        3,
    ),
    (
        "Check TLS 1.3 support on example.com and list all available cipher suites",
        ["openssl", "nmap", "nmap"],
        3,
        3,
    ),
    # ===== SECTION 9: CERTIFICATE TRANSPARENCY (12) =====
    ("certificate transparency search for example.com", ["curl"], 1, 1),
    ("crtsh lookup for example.com", ["curl"], 1, 1),
    ("crt.sh search for example.com", ["curl"], 1, 1),
    ("certificate log inspection for example.com", ["openssl"], 1, 1),
    ("crtsh certificate search for example.com", ["curl"], 1, 1),
    ("certificate transparency logs for example.com", ["curl"], 1, 1),
    ("crt.sh domain search for example.com", ["curl"], 1, 1),
    ("ssl certificate transparency for example.com", ["openssl", "nmap", "nmap"], 3, 3),
    ("Search certificate transparency logs on crt.sh for example.com subdomains", ["curl"], 1, 1),
    ("Use crt.sh to find all SSL certificates issued for example.com", ["curl"], 1, 1),
    (
        "Query CT logs for example.com to discover subdomains and expired certs",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    (
        "Monitor certificate transparency logs for new certificates issued to example.com",
        ["curl"],
        1,
        1,
    ),
    # ===== SECTION 10: URL DISCOVERY & WAYBACK (18) =====
    ("wayback machine urls for example.com", ["waybackurls"], 1, 1),
    ("gau url discovery for example.com", ["gau"], 1, 1),
    ("get all urls for example.com", ["gau"], 1, 1),
    ("waybackurls discovery on example.com", ["waybackurls"], 1, 1),
    ("gau wayback url discovery for example.com", ["gau"], 1, 1),
    ("wayback machine endpoints for example.com", ["waybackurls"], 1, 1),
    ("historic urls for example.com from archive", ["gau"], 1, 1),
    ("url enumeration on example.com from wayback", ["waybackurls"], 1, 1),
    ("gau wayback url discovery for example.com", ["gau"], 1, 1),
    ("Fetch all historical URLs for example.com from Wayback Machine", ["waybackurls"], 1, 1),
    ("Use gau to get every URL ever seen for example.com", ["gau"], 1, 1),
    ("I need to find old endpoints and archived pages for example.com", ["gobuster"], 1, 1),
    ("Discover all URLs for example.com from the Wayback Machine archive", ["waybackurls"], 1, 1),
    (
        "Extract all JavaScript URLs and API endpoints from wayback data for example.com",
        ["waybackurls"],
        1,
        1,
    ),
    ("Get the complete URL history for example.com including hidden paths", ["gau"], 1, 1),
    (
        "Wayback Machine URL discovery for example.com to find forgotten endpoints",
        ["waybackurls"],
        1,
        1,
    ),
    (
        "Use gau to collect all URLs for example.com and then filter for interesting parameters",
        ["gau", "arjun"],
        2,
        2,
    ),
    ("Pull wayback URLs then probe with httpx for live endpoints", ["waybackurls", "httpx"], 2, 2),
    # ===== SECTION 11: HTTP PROBING & CRAWLING (16) =====
    ("httpx probe on https://example.com", ["httpx"], 1, 1),
    ("http probe on example.com", ["httpx"], 1, 1),
    ("web crawl with katana on https://example.com", ["katana"], 1, 1),
    ("spider with gospider on https://example.com", ["gospider"], 1, 1),
    ("httpx live host probing for example.com", ["httpx"], 1, 1),
    ("katana crawl example.com for endpoints", ["katana"], 1, 1),
    ("gospider web spider on https://example.com", ["gospider"], 1, 1),
    ("probe all subdomains for example.com with httpx", ["httpx"], 1, 1),
    ("crawl and spider example.com", ["katana"], 1, 1),
    ("httpx tech detection on https://example.com", ["httpx"], 1, 1),
    ("katana url discovery on example.com", ["katana"], 1, 1),
    ("gospider content discovery on https://example.com", ["gospider"], 1, 1),
    (
        "Probe https://example.com with httpx to get status codes and tech detection",
        ["httpx"],
        1,
        1,
    ),
    ("Crawl example.com with katana to discover all accessible endpoints", ["katana"], 1, 1),
    (
        "Spider the entire https://example.com site with gospider for content discovery",
        ["gospider"],
        1,
        1,
    ),
    (
        "JavaScript endpoint discovery on https://example.com - find JS files and endpoints",
        ["gospider"],
        1,
        1,
    ),
    # ===== SECTION 12: PARAMETER DISCOVERY (12) =====
    ("arjun parameter discovery on https://example.com", ["arjun"], 1, 1),
    ("paramspider mining on example.com", ["paramspider"], 1, 1),
    ("discover http parameter on https://example.com", ["arjun"], 1, 1),
    ("param mining on example.com", ["arjun"], 1, 1),
    ("arjun find hidden params on https://example.com", ["arjun"], 1, 1),
    ("parameter discovery scan on example.com", ["arjun"], 1, 1),
    ("url parameter enumeration on https://example.com", ["arjun"], 1, 1),
    ("get params from url on https://example.com", ["arjun"], 1, 1),
    ("Find hidden GET and POST parameters on https://example.com with arjun", ["arjun"], 1, 1),
    ("Use paramspider to mine URLs for common parameters on example.com", ["paramspider"], 1, 1),
    (
        "Discover URL parameters for https://example.com to find hidden functionality",
        ["arjun"],
        1,
        1,
    ),
    (
        "Parameter fuzzing on https://example.com to discover undocumented parameters",
        ["arjun"],
        1,
        1,
    ),
    # ===== SECTION 13: CLOUD RECON (16) =====
    ("cloud audit on https://example.com", ["curl", "whatweb", "dig", "openssl"], 4, 4),
    ("aws metadata check on http://169.254.169.254", ["curl", "whatweb", "dig", "openssl"], 4, 4),
    ("azure metadata check on 169.254.169.254", ["curl", "whatweb", "dig", "openssl"], 4, 4),
    ("gcp metadata check on metadata.google.internal", ["curl", "whatweb", "dig", "openssl"], 4, 4),
    ("cloudfront detection for example.com", ["curl"], 1, 1),
    ("s3 bucket enumeration for example", ["curl", "whatweb", "dig", "openssl"], 4, 4),
    ("cloud storage audit on example", ["curl", "whatweb", "dig", "openssl"], 4, 4),
    ("cloud_enum storage scan for example", ["cloud_enum"], 1, 1),
    ("scoutsuite cloud audit for aws", ["scoutsuite"], 1, 1),
    ("prowler aws security audit", ["prowler"], 1, 1),
    ("cdn detection for cdn.example.com", ["curl"], 1, 1),
    (
        "azure blob check on https://test.blob.core.windows.net",
        ["curl", "whatweb", "dig", "openssl"],
        4,
        4,
    ),
    ("gcp bucket scan on storage.googleapis.com", ["curl", "whatweb", "dig", "openssl"], 4, 4),
    (
        "Check if example.com uses any cloud services like AWS CloudFront or Azure",
        ["curl", "whatweb", "dig", "openssl"],
        4,
        4,
    ),
    (
        "Enumerate S3 buckets for example to find open storage",
        ["curl", "whatweb", "dig", "openssl"],
        4,
        4,
    ),
    (
        "I need to audit the cloud infrastructure of example.com including CDN and storage",
        ["curl", "whatweb", "dig", "openssl"],
        4,
        4,
    ),
    # ===== SECTION 14: SHODAN / CENSYS / UNCOVER (12) =====
    ("shodan search for example.com on internet", ["shodan"], 1, 1),
    ("shodan internet device search for example.com", ["shodan"], 1, 1),
    ("censys search for example.com certificates", ["censys"], 1, 1),
    ("censys ip lookup for 8.8.8.8", ["censys"], 1, 1),
    ("shodan port scan history for 8.8.8.8", ["shodan"], 1, 1),
    ("shodan honeypot check for 8.8.8.8", ["shodan"], 1, 1),
    ("uncover search for example.com", ["uncover"], 1, 1),
    ("shodan and censys search on example.com", ["shodan"], 1, 1),
    ("Search Shodan for all exposed services on example.com's IP range", ["shodan"], 1, 1),
    ("Use Censys to find all certificates and services for example.com", ["censys"], 1, 1),
    ("Run uncover to discover assets for example.com from Shodan and Censys", ["uncover"], 1, 1),
    (
        "I need to find all internet-facing infrastructure for example.com using Shodan",
        ["shodan"],
        1,
        1,
    ),
    # ===== SECTION 15: EMAIL OSINT (14) =====
    ("theHarvester email osint on example.com", ["theHarvester"], 1, 1),
    ("the harvester harvest on example.com", ["theHarvester"], 1, 1),
    ("email osint harvesting for example.com", ["theHarvester"], 1, 1),
    ("email recon on example.com", ["theHarvester", "dig", "nmap", "dig"], 4, 4),
    ("email harvest on example.com", ["theHarvester", "dig", "nmap", "dig"], 4, 4),
    ("smtp enum on mail.example.com", ["theHarvester", "dig", "nmap", "dig"], 4, 4),
    ("mail server discovery for example.com", ["theHarvester", "dig", "nmap", "dig"], 4, 4),
    ("holehe email check for user@example.com", ["holehe"], 1, 1),
    ("theHarvester email search on example.com", ["theHarvester"], 1, 1),
    ("enumerate emails on example.com", ["theHarvester"], 1, 1),
    ("find email addresses on example.com", ["theHarvester"], 1, 1),
    (
        "Gather all email addresses associated with example.com using theHarvester",
        ["theHarvester"],
        1,
        1,
    ),
    ("Check if user@example.com is registered on popular websites using holehe", ["holehe"], 1, 1),
    (
        "I need to find employees email addresses for example.com for the phishing assessment",
        ["theHarvester"],
        1,
        1,
    ),
    # ===== SECTION 16: USERNAME / SOCIAL OSINT (12) =====
    ("sherlock username search for johndoe", ["sherlock"], 1, 1),
    ("maigret user search for johndoe", ["maigret"], 1, 1),
    ("social media lookup for johndoe", ["sherlock"], 1, 1),
    ("social media lookup for johndoe across platforms", ["sherlock"], 1, 1),
    ("social network search for johndoe on social media", ["sherlock"], 1, 1),
    ("find all accounts for johndoe across networks", ["sherlock"], 1, 1),
    (
        "digital footprint search for johndoe online",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    ("osint username reconnaissance for johndoe on social medias", ["sherlock"], 1, 1),
    (
        "Find all social media profiles for username johndoe across 400+ platforms",
        ["sherlock"],
        1,
        1,
    ),
    ("Use maigret to perform a comprehensive username search for johndoe", ["maigret"], 1, 1),
    ("Search for johndoe across social networks and online platforms", ["sherlock"], 1, 1),
    (
        "I need to build a digital footprint profile for johndoe using OSINT techniques",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    # ===== SECTION 17: SECRET SCANNING (12) =====
    ("trufflehog secret scan on git repo", ["trufflehog"], 1, 1),
    ("gitleaks scan on repository", ["gitleaks"], 1, 1),
    ("git secret scanning on repo", ["trufflehog"], 1, 1),
    ("find leaked secrets in repo", ["trufflehog"], 1, 1),
    ("trufflehog git history scan for credentials", ["trufflehog"], 1, 1),
    ("gitleaks git secrets detection", ["gitleaks"], 1, 1),
    ("scan for api keys in repository", ["trufflehog"], 1, 1),
    ("credential leak detection in git repo", ["trufflehog"], 1, 1),
    ("Scan the repository for leaked API keys and secrets using trufflehog", ["trufflehog"], 1, 1),
    ("Run gitleaks on the repo to detect hardcoded passwords and tokens", ["gitleaks"], 1, 1),
    (
        "Find leaked credentials in our github repository before the security audit",
        ["nmap", "curl", "whatweb", "nuclei", "gobuster", "dig", "subfinder", "whois"],
        8,
        8,
    ),
    ("We need to scan git history for any accidentally committed secrets", ["trufflehog"], 1, 1),
    # ===== SECTION 18: ACTIVE DIRECTORY RECON (16) =====
    ("active directory assessment on 10.0.0.1", ["nmap", "nmap", "nmap", "nmap"], 4, 4),
    ("ad recon on domain controller 10.0.0.5", ["nmap", "nmap", "nmap", "nmap"], 4, 4),
    ("ldap enum on 10.0.0.1", ["nmap"], 1, 1),
    ("kerberos user enum on 10.0.0.1", ["nmap"], 1, 1),
    ("smb share enum on 10.0.0.1", ["nmap", "nmap", "nmap", "nmap"], 4, 4),
    ("smb enum on windows server 10.0.0.1", ["nmap", "nmap", "nmap", "nmap"], 4, 4),
    ("netbios scan on 10.0.0.1", ["nmap", "nmap", "nmap", "nmap"], 4, 4),
    ("responder capture on eth0", ["responder"], 1, 1),
    ("impacket enumeration on dc.example.com", ["impacket"], 1, 1),
    ("enum4linux recon on 10.0.0.1", ["nmap", "nmap", "nmap", "nmap"], 4, 4),
    ("ldap domain dump on dc.example.com", ["nmap"], 1, 1),
    ("crackmapexec smb enum on 10.0.0.1", ["nmap", "nmap", "nmap", "nmap"], 4, 4),
    ("netexec ad recon on 10.0.0.1", ["nmap", "nmap", "nmap", "nmap"], 4, 4),
    (
        "Enumerate SMB shares and users on 10.0.0.1 for privilege escalation",
        ["nmap", "nmap", "nmap", "nmap"],
        4,
        4,
    ),
    ("Perform LDAP anonymous bind check on dc.example.com to enumerate users", ["nmap"], 1, 1),
    ("Run responder to capture LLMNR/NBT-NS traffic on the network", ["responder"], 1, 1),
    # ===== SECTION 19: VULNERABILITY RECON (16) =====
    ("vuln scan on https://example.com", ["nuclei", "nikto", "wpscan", "sqlmap"], 4, 4),
    ("cve scan on https://example.com", ["nuclei", "nikto", "wpscan", "sqlmap"], 4, 4),
    ("log4j check on https://example.com", ["nuclei"], 1, 1),
    ("heartbleed test on https://example.com", ["nmap"], 1, 1),
    ("shellshock scan on https://example.com", ["nuclei"], 1, 1),
    ("spring4shell check on https://example.com", ["nuclei"], 1, 1),
    (
        "struts vulnerability scan on https://example.com",
        ["nuclei", "nikto", "wpscan", "sqlmap"],
        4,
        4,
    ),
    ("searchsploit apache 2.4.49", ["searchsploit"], 1, 1),
    ("exploit search for wordpress 5.8", ["searchsploit"], 1, 1),
    ("ssrf check on https://example.com", ["nuclei"], 1, 1),
    ("idor scan on https://example.com/api", ["nuclei"], 1, 1),
    ("lfi scan on https://example.com/page", ["nuclei"], 1, 1),
    ("rfi scan on https://example.com/page", ["nuclei"], 1, 1),
    ("open redirect scan on https://example.com", ["nuclei"], 1, 1),
    ("deserialization check on https://example.com", ["nuclei"], 1, 1),
    ("broken access control check on https://example.com", ["nuclei"], 1, 1),
    # ===== SECTION 20: WEB APP VULN SCANNING (10) =====
    (
        "web audit on https://example.com",
        ["curl", "whatweb", "nuclei", "ffuf", "wpscan", "nikto"],
        6,
        6,
    ),
    (
        "web scan on https://example.com",
        ["curl", "whatweb", "nuclei", "ffuf", "wpscan", "nikto"],
        6,
        6,
    ),
    (
        "full web audit on https://example.com",
        ["curl", "whatweb", "nuclei", "ffuf", "wpscan", "nikto"],
        6,
        6,
    ),
    ("nikto vulnerability scan on https://example.com", ["nikto"], 1, 1),
    ("nuclei scan on https://example.com", ["nuclei"], 1, 1),
    (
        "Run a comprehensive web application scan on https://example.com",
        ["curl", "whatweb", "nuclei", "ffuf", "wpscan", "nikto"],
        6,
        6,
    ),
    (
        "I need a full web audit of example.com including headers, vulns, and directories",
        ["curl", "whatweb", "nuclei", "ffuf", "wpscan", "nikto"],
        6,
        6,
    ),
    (
        "Do a vulnerability assessment on https://example.com with nuclei templates",
        ["nuclei"],
        1,
        1,
    ),
    (
        "Web application security scan for example.com - find all OWASP Top 10 issues",
        ["curl", "whatweb", "nuclei", "ffuf", "wpscan", "nikto"],
        6,
        6,
    ),
    ("Run nikto for a full web server vulnerability scan on https://example.com", ["nikto"], 1, 1),
    # ===== SECTION 21: EXTERNAL / PASSIVE / FULL RECON (18) =====
    (
        "external recon on example.com",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    (
        "external attack surface on example.com",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    ("passive recon on example.com", ["whatweb", "subfinder", "dig", "whois", "openssl"], 5, 5),
    (
        "passive reconnaissance on example.com",
        ["whatweb", "subfinder", "dig", "whois", "openssl"],
        5,
        5,
    ),
    (
        "osint recon on example.com",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "full osint recon on example.com",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "external attack surface recon on example.com",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    ("passive scan on example.com", ["whatweb", "subfinder", "dig", "whois", "openssl"], 5, 5),
    (
        "full recon on example.com",
        ["nmap", "curl", "whatweb", "nuclei", "gobuster", "dig", "subfinder", "whois"],
        8,
        8,
    ),
    (
        "comprehensive recon on example.com",
        ["nmap", "curl", "whatweb", "nuclei", "gobuster", "dig", "subfinder", "whois"],
        8,
        8,
    ),
    (
        "Map the entire external attack surface for example.com including Shodan and certificates",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    (
        "Do passive intelligence gathering on example.com without any active scanning",
        ["whatweb", "subfinder", "dig", "whois", "openssl"],
        5,
        5,
    ),
    (
        "Full open source intelligence gathering for example.com",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "Initial access OSINT on example.com for the red team engagement",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    (
        "Pre engagement reconnaissance on example.com to gather threat intel",
        ["whatweb", "subfinder", "dig", "whois", "openssl"],
        5,
        5,
    ),
    (
        "Attack surface mapping for example.com across all external assets",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    (
        "Stealth passive recon on example.com using only non-intrusive techniques",
        ["whatweb", "subfinder", "dig", "whois", "openssl"],
        5,
        5,
    ),
    (
        "Red team external recon on example.com to discover perimeter weaknesses",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    # ===== SECTION 22: COMPOUND MULTI-TOOL (20) =====
    ("subfinder then httpx on example.com", ["subfinder", "httpx"], 2, 2),
    ("gau then httpx on example.com", ["gau", "httpx"], 2, 2),
    ("waybackurls then httpx on example.com", ["waybackurls", "httpx"], 2, 2),
    ("theHarvester and then holehe on example.com", ["theHarvester", "holehe"], 2, 2),
    ("amass subdomains and then httpx probe on example.com", ["amass", "httpx"], 2, 2),
    ("gau and then katana on example.com", ["gau", "katana"], 2, 2),
    ("subfinder and then gospider on example.com", ["subfinder", "gospider"], 2, 2),
    ("dnsx then httpx on example.com", ["dnsx", "httpx"], 2, 2),
    ("massdns then puredns on example.com", ["massdns", "puredns"], 2, 2),
    ("uncover then httpx on example.com", ["uncover", "httpx"], 2, 2),
    ("theHarvester then sherlock for johndoe", ["theHarvester", "sherlock"], 2, 2),
    ("crtsh and then httpx on example.com", ["curl", "httpx"], 2, 2),
    ("subdomain enumeration then port scan on example.com", ["subfinder", "nmap"], 2, 2),
    ("whois lookup then ssl check on example.com", ["whois", "openssl"], 2, 2),
    ("discover urls then find parameters on https://example.com", ["gau", "arjun"], 2, 2),
    ("enumerate subdomains then probe with httpx on example.com", ["subfinder", "httpx"], 2, 2),
    ("subdomain brute force with amass then httpx probe on example.com", ["amass", "httpx"], 2, 2),
    ("find emails then check subdomains on example.com", ["theHarvester", "subfinder"], 2, 2),
    ("gau then waybackurls on example.com", ["gau", "waybackurls"], 2, 2),
    ("crtsh certificate search then httpx probe on example.com", ["curl", "httpx"], 2, 2),
    # ===== SECTION 23: ADVANCED PROFESSIONAL WORKFLOWS (18) =====
    (
        "We are doing a red team engagement on example.com, start with external recon",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    (
        "I need to understand the security posture of example.com, do a comprehensive assessment",
        ["nmap", "curl", "whatweb", "nuclei", "gobuster", "dig", "subfinder", "whois"],
        8,
        8,
    ),
    (
        "I am starting a penetration test on example.com, map out the attack surface first",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    (
        "Before the pentest, do pre-engagement OSINT on example.com to gather intel silently",
        ["nmap", "curl", "whatweb", "nuclei", "gobuster", "dig", "subfinder", "whois"],
        8,
        8,
    ),
    (
        "Automated recon pipeline for example.com: subdomains, httpx probe, nuclei scan, screenshots",
        ["httpx"],
        1,
        1,
    ),
    (
        "Full scope external recon for example.com - find all assets, subdomains, and exposed services",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    (
        "Comprehensive passive recon on example.com without touching the target infrastructure",
        ["whatweb", "subfinder", "dig", "whois", "openssl"],
        5,
        5,
    ),
    (
        "Multi-vector external recon on example.com using Shodan, CT logs, and passive DNS",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    (
        "OSINT profiling for example.com: gather domains, emails, tech stack, and SSL certs",
        ["openssl", "nmap", "nmap"],
        3,
        3,
    ),
    (
        "Adversary reconnaissance on example.com to understand the target from an attacker perspective",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "I need to map example.com's cloud infrastructure - check AWS, Azure, GCP services",
        ["curl", "whatweb", "dig", "openssl"],
        4,
        4,
    ),
    (
        "Bug bounty recon on example.com: subdomains, wayback urls, parameter discovery",
        ["waybackurls"],
        1,
        1,
    ),
    (
        "Zero-touch OSINT automation for example.com - all passive intelligence gathering",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "Complete digital footprint analysis of example.com across the entire internet",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "Continuous recon monitoring for example.com - track changes in external assets",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "Tier 1 OSINT collection for example.com: gather all publicly available information",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "Reconnaissance lifecycle for example.com - full intelligence gathering lifecycle",
        ["whois", "dig", "dig", "curl", "subfinder", "amass", "whatweb"],
        7,
        7,
    ),
    (
        "Attack surface discovery for example.com - perimeter mapping and external assessment",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    # ===== SECTION 24: NATURAL LANGUAGE TASKS (28) =====
    (
        "Check what services are running on 10.0.0.1 and identify the operating system",
        ["nmap"],
        1,
        1,
    ),
    (
        "Find all DNS records for example.com including MX, TXT, NS, and CNAME",
        ["dig", "subfinder", "amass", "whois"],
        4,
        4,
    ),
    (
        "I need to find all subdomains for example.com and check which ones return HTTP 200",
        ["nmap", "whatweb", "gobuster", "subfinder", "amass", "nuclei"],
        6,
        6,
    ),
    (
        "Can you scan example.com for open ports and then check what web technologies they use?",
        ["nmap", "whatweb"],
        2,
        2,
    ),
    (
        "Do a complete security analysis of example.com including headers, SSL, and vulnerabilities",
        ["openssl", "nmap", "nmap"],
        3,
        3,
    ),
    (
        "Find all JavaScript files on https://example.com and extract API endpoints from them",
        ["gospider"],
        1,
        1,
    ),
    (
        "I need to enumerate SMB shares on 10.0.0.1 and check for null session access",
        ["nmap", "nmap", "nmap", "nmap"],
        4,
        4,
    ),
    ("Check if example.com has any exposed .git directories or backup files", ["curl"], 1, 1),
    (
        "Run a vulnerability scan on https://example.com for critical and high severity issues only",
        ["nuclei", "nikto", "wpscan", "sqlmap"],
        4,
        4,
    ),
    (
        "Discover all API endpoints on https://example.com including REST and GraphQL",
        ["curl"],
        1,
        1,
    ),
    ("I need to test whether example.com is vulnerable to subdomain takeover", ["subjack"], 1, 1),
    (
        "Find all email addresses associated with example.com and verify if they are valid",
        ["theHarvester"],
        1,
        1,
    ),
    (
        "Do a full reconnaissance on example.com and provide a comprehensive report",
        ["nmap", "curl", "whatweb", "nuclei", "gobuster", "dig", "subfinder", "whois"],
        8,
        8,
    ),
    (
        "Check if example.com has any cloud storage buckets open to the public",
        ["curl", "whatweb", "dig", "openssl"],
        4,
        4,
    ),
    (
        "I need to find the technology stack behind example.com including web server and frameworks",
        ["whatweb"],
        1,
        1,
    ),
    (
        "Test all cipher suites supported by example.com and check for weak TLS configurations",
        ["openssl", "nmap", "nmap"],
        3,
        3,
    ),
    (
        "Find historical URLs for example.com from the Wayback Machine that might contain sensitive data",
        ["waybackurls"],
        1,
        1,
    ),
    (
        "I need to map the external attack surface of example.com using Shodan and certificate logs",
        ["shodan"],
        1,
        1,
    ),
    (
        "Check if the target 10.0.0.1 is vulnerable to EternalBlue or other SMB exploits",
        ["nmap", "nmap", "nmap", "nmap"],
        4,
        4,
    ),
    (
        "Do passive OSINT on example.com without generating any traffic to their servers",
        ["whatweb", "subfinder", "dig", "whois", "openssl"],
        5,
        5,
    ),
    (
        "Enumerate all LDAP information from dc.example.com including users and groups",
        ["nmap"],
        1,
        1,
    ),
    (
        "I need to find API keys and tokens that were accidentally committed to the git repository",
        ["trufflehog"],
        1,
        1,
    ),
    (
        "Check example.com's SSL certificate chain and validate it against trusted root CAs",
        ["openssl", "nmap", "nmap"],
        3,
        3,
    ),
    (
        "Find all parameters accepted by https://example.com/endpoint using param mining",
        ["gobuster"],
        1,
        1,
    ),
    (
        "I'm doing a bug bounty assessment on example.com, start with subdomain enumeration and httpx probing",
        ["httpx"],
        1,
        1,
    ),
    ("Check if the docker daemon is exposed on 10.0.0.1 and enumerate containers", ["cat"], 1, 1),
    (
        "Perform a complete passive reconnaissance on example.com for red team preparation",
        ["shodan", "curl", "whatweb", "subfinder", "whois", "dig"],
        6,
        6,
    ),
    (
        "I need to discover all cloud assets of example.com including S3, Azure Blob, and GCP buckets",
        ["curl", "whatweb", "dig", "openssl"],
        4,
        4,
    ),
    # ===== SECTION 25: SPECIALIZED / EDGE CASE (24) =====
    ("quick check on https://example.com", ["curl"], 1, 1),
    ("interactsh oob testing client", ["interactsh"], 1, 1),
    ("exposed panels scan on https://example.com", ["nuclei"], 1, 1),
    ("broken access control scan on https://example.com", ["nuclei"], 1, 1),
    ("oauth endpoint enum on https://example.com", ["nmap"], 1, 1),
    ("smtp user enum on mail.example.com", ["nmap"], 1, 1),
    ("waf detection on https://example.com", ["nmap"], 1, 1),
    ("cdn detection for https://example.com", ["curl"], 1, 1),
    ("docker discovery on 10.0.0.1:2375", ["nmap"], 1, 1),
    ("jenkins discovery on jenkins.example.com", ["nmap"], 1, 1),
    ("redis enumeration on 10.0.0.1:6379", ["nmap"], 1, 1),
    ("mongodb enum on 10.0.0.1:27017", ["nmap"], 1, 1),
    ("mysql scan on 10.0.0.1:3306", ["nmap"], 1, 1),
    ("mssql discovery on 10.0.0.1:1433", ["nmap"], 1, 1),
    ("elasticsearch discovery on 10.0.0.1:9200", ["curl"], 1, 1),
    ("postgresql enum on 10.0.0.1:5432", ["nmap"], 1, 1),
    ("kafka discovery on 10.0.0.1:9092", ["nmap"], 1, 1),
    ("rabbitmq discovery on 10.0.0.1:5672", ["nmap"], 1, 1),
    ("cassandra scan on 10.0.0.1:9042", ["nmap"], 1, 1),
    ("graphql introspection on https://example.com", ["curl"], 1, 1),
    ("swagger discovery on https://example.com", ["curl"], 1, 1),
    ("websocket upgrade check on https://example.com", ["curl"], 1, 1),
    ("server header check on https://example.com", ["whatweb"], 1, 1),
    ("container discovery on 10.0.0.1", ["nmap"], 1, 1),
]


def main():
    planner = RegistryPlanner()
    planner.build_index(AVAILABLE_TOOLS)

    passed = 0
    failed = 0
    failures = []

    total = len(RECON_COMMANDS)
    print(f"\n{'=' * 60}")
    print(f"  RECON NLP EVALUATION: {total} Commands")
    print(f"{'=' * 60}\n")

    for idx, (cmd, expected_tools, min_steps, max_steps) in enumerate(RECON_COMMANDS):
        ok, msg = check_plan(planner, cmd, expected_tools, min_steps, max_steps)
        if ok:
            passed += 1
        else:
            failed += 1
            failures.append((cmd, msg))
        status = "PASS" if ok else "FAIL"
        print(f"  [{status:4s}] ({idx + 1:3d}) {cmd:75s} \u2192 {msg}")

    print(f"\n{'=' * 60}")
    print(f"  RESULTS: {passed} passed, {failed} failed out of {total}")
    print(f"  SCORE: {passed / total * 100:.1f}%")
    print(f"{'=' * 60}\n")

    if failures:
        print("FAILED COMMANDS:")
        for cmd, msg in failures:
            print(f"  - {cmd}")
            print(f"    Reason: {msg}")
        print()

    return failed == 0


if __name__ == "__main__":
    success = main()
    sys.exit(0 if success else 1)
