"""Execution engine — combines autonomous task planning with registry-based
tool execution.

This is the core of the execution architecture:

- **Registry mode**: Uses the tool registry directly for known tools.
- **Autonomous mode**: Model-driven planning and execution.
- **Integrated mode** (default): Model-driven planning for complex tasks with
  registry-based execution for known tools and intelligent fallback.

The engine provides a unified execution interface regardless of whether the
plan was generated by a model or from the static registry.
"""

from __future__ import annotations

import asyncio
import json
import logging
import time
import uuid
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.progress import Progress, SpinnerColumn, TextColumn, TimeElapsedColumn
from rich.table import Table

from .planner import (
    TaskPlanner,
    CloudModel,
    GeminiModel,
    ExecutionPlan,
    ExecutionStep,
    OllamaModel,
    OpenAIModel,
    StepType,
)
from .dynamic_resolver import DynamicResolver
from .executor import run_tool_complete
from .metrics import get_metrics
from .offline_store import OfflineStore
from .tool_registry import ToolInfo, ToolRegistry

logger = logging.getLogger(__name__)
console = Console()

# Maximum characters of output to include in model analysis context per step
_MAX_CONTEXT_OUTPUT_LENGTH = 2000

# Retry configuration
_MAX_RETRIES = 3
_RETRY_BACKOFF_FACTOR = 2.0
_RETRY_BASE_DELAY = 1.0  # seconds
_RETRY_MAX_DELAY = 30.0  # seconds


class ExecutionMode(StrEnum):
    """Execution mode for the engine."""

    REGISTRY = "registry"  # Registry-only (no model-driven planning)
    AUTONOMOUS = "autonomous"  # Model-driven planning and execution
    INTEGRATED = "integrated"  # Model-driven planning with registry fallback


class StepStatus(StrEnum):
    """Status of an execution step."""

    PENDING = "pending"
    RUNNING = "running"
    SUCCESS = "success"
    FAILED = "failed"
    SKIPPED = "skipped"
    BLOCKED = "blocked"


@dataclass
class StepResult:
    """Result of executing a single step."""

    step_id: str
    status: StepStatus
    output: str = ""
    error: str = ""
    duration_ms: float = 0.0
    findings: list[dict[str, Any]] = field(default_factory=list)
    metadata: dict[str, Any] = field(default_factory=dict)
    retry_count: int = 0  # How many times this step was retried
    exit_code: int | None = None  # Tool exit code if applicable


@dataclass
class EngineResult:
    """Aggregate result of executing an entire plan."""

    plan: ExecutionPlan
    step_results: list[StepResult] = field(default_factory=list)
    total_duration_ms: float = 0.0
    mode: ExecutionMode = ExecutionMode.INTEGRATED
    all_findings: list[dict[str, Any]] = field(default_factory=list)
    plan_id: str | None = None  # Plan ID for persistence
    retries_performed: int = 0  # Total retries across all steps

    @property
    def success(self) -> bool:
        return all(r.status in (StepStatus.SUCCESS, StepStatus.SKIPPED) for r in self.step_results)

    @property
    def summary(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for r in self.step_results:
            counts[r.status.value] = counts.get(r.status.value, 0) + 1
        return counts

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage/serialization."""
        return {
            "plan_id": self.plan_id,
            "plan": self.plan.to_dict(),
            "step_results": [
                {
                    "step_id": r.step_id,
                    "status": r.status.value,
                    "output": r.output[:1000],  # Truncate for storage
                    "error": r.error,
                    "duration_ms": r.duration_ms,
                    "findings": r.findings,
                    "retry_count": r.retry_count,
                    "exit_code": r.exit_code,
                }
                for r in self.step_results
            ],
            "total_duration_ms": self.total_duration_ms,
            "mode": self.mode.value,
            "success": self.success,
            "retries_performed": self.retries_performed,
        }


class ExecutionEngine:
    """The core execution engine.

    Combines model-driven autonomous planning with registry-based execution.
    Supports three modes: registry, autonomous, and integrated (default).

    Usage::

        engine = ExecutionEngine()
        result = await engine.execute("scan 192.168.1.1 with nmap then analyze results")
    """

    def __init__(
        self,
        mode: ExecutionMode = ExecutionMode.INTEGRATED,
        registry: ToolRegistry | None = None,
        config: dict[str, Any] | None = None,
    ) -> None:
        self._mode = mode
        self._registry = registry or ToolRegistry()
        self._config = config or {}

        # Discover tools and build context
        fast_discovery = bool(self._config.get("fast_discovery"))
        self._discovered_tools = self._registry.discover(fast=fast_discovery)
        self._tool_map: dict[str, ToolInfo] = {t.name: t for t in self._discovered_tools}
        self._binary_map: dict[str, ToolInfo] = {t.binary: t for t in self._discovered_tools}

        # Initialize task planner with providers
        self._planner = TaskPlanner()
        self._setup_providers()

        # Initialize dynamic resolver
        registered = {t.binary: t.path for t in self._discovered_tools}
        registered.update({t.name: t.path for t in self._discovered_tools})
        self._resolver = DynamicResolver(registered_tools=registered)

        # Step results for tracking
        self._completed_steps: dict[str, StepResult] = {}
        self._offline_store: OfflineStore | None = None

    def _get_offline_store(self) -> OfflineStore:
        """Get or create offline store instance."""
        if self._offline_store is None:
            self._offline_store = OfflineStore()
        return self._offline_store

    def _setup_providers(self) -> None:
        """Configure model providers based on available configuration."""
        # OpenAI
        openai_key = self._config.get("openai_api_key", "")
        openai_model = self._config.get("openai_model", "gpt-4o")
        openai_provider = OpenAIModel(api_key=openai_key, model=openai_model)

        # Ollama (local)
        ollama_url = self._config.get("ollama_url", "http://localhost:11434")
        ollama_model = self._config.get("ollama_model", "llama3.1")
        ollama_provider = OllamaModel(base_url=ollama_url, model=ollama_model)

        # Cloud service
        cloud_url = self._config.get("server_url", "")
        cloud_key = self._config.get("api_key", "")
        cloud_provider = CloudModel(server_url=cloud_url, api_key=cloud_key)

        preferred = str(self._config.get("model_provider", "auto")).strip().lower()
        gemini_key = self._config.get("gemini_api_key", "")
        gemini_model = self._config.get("gemini_model", "gemini-1.5-pro")
        gemini_provider = GeminiModel(api_key=gemini_key, model=gemini_model)

        ordered_providers = [gemini_provider, openai_provider, ollama_provider, cloud_provider]
        preference_map = {
            "gemini": [gemini_provider, openai_provider, ollama_provider, cloud_provider],
            "openai": [openai_provider, gemini_provider, ollama_provider, cloud_provider],
            "ollama": [ollama_provider, gemini_provider, openai_provider, cloud_provider],
            "cloud": [cloud_provider, gemini_provider, openai_provider, ollama_provider],
            "auto": ordered_providers,
        }

        for provider in preference_map.get(preferred, ordered_providers):
            if hasattr(provider, "available") and not provider.available:
                continue
            self._planner.add_provider(provider)

    @property
    def mode(self) -> ExecutionMode:
        return self._mode

    @property
    def discovered_tools(self) -> list[ToolInfo]:
        return self._discovered_tools

    def _build_context(self) -> dict[str, Any]:
        """Build context dict for the task planner."""
        return {
            "available_tools": [
                {
                    "name": t.name,
                    "binary": t.binary,
                    "capabilities": t.capabilities,
                    "version": t.version,
                }
                for t in self._discovered_tools
            ],
            "mode": self._mode.value,
        }

    async def plan(self, instruction: str) -> ExecutionPlan:
        """Create an execution plan for the given instruction.

        This is the planning phase — no execution happens here.
        """
        context = self._build_context()
        force_mode = None
        if self._mode == ExecutionMode.REGISTRY:
            force_mode = "static"
        elif self._mode == ExecutionMode.AUTONOMOUS:
            force_mode = "autonomous"

        return await self._planner.plan(instruction, context, force_mode)

    async def execute(
        self,
        instruction: str,
        interactive: bool = True,
        dry_run: bool = False,
        persist: bool = False,
    ) -> EngineResult:
        """Plan and execute a natural language instruction.

        Parameters
        ----------
        instruction:
            The user's natural language command.
        interactive:
            If True, show progress and prompt for unsafe commands.
        dry_run:
            If True, plan only — don't execute.
        """
        start_time = time.monotonic()
        persist_workflow = persist or bool(self._config.get("persist_workflows"))
        store = self._get_offline_store() if persist_workflow else None
        plan_id: str | None = None

        # Phase 1: Plan
        plan = await self.plan(instruction)

        if interactive:
            self._display_plan(plan)

        if persist_workflow:
            plan_id = str(uuid.uuid4())
            # Narrow type for mypy: ensure store is not None before calling persistence API
            assert store is not None
            store.save_plan(
                plan_id=plan_id,
                instruction=instruction,
                plan_json=json.dumps(plan.to_dict()),
                status="planned",
            )

        if dry_run:
            result = EngineResult(plan=plan, mode=self._mode)
            result.plan_id = plan_id
            return result

        if not plan.steps:
            if interactive:
                console.print(
                    "[yellow]Could not create an execution plan from your instruction.[/yellow]\n"
                    "[dim]Tip: Try being more specific, e.g. "
                    "'scan 192.168.1.1 with nmap and nuclei'[/dim]"
                )
            result = EngineResult(plan=plan, mode=self._mode)
            result.plan_id = plan_id
            return result

        # Phase 2: Execute
        self._completed_steps.clear()
        result = EngineResult(plan=plan, mode=self._mode)
        result.plan_id = plan_id

        if persist_workflow and plan_id:
            assert store is not None
            store.update_plan_status(plan_id, status="running")

        if interactive:
            with Progress(
                SpinnerColumn(),
                TextColumn("[bold cyan]{task.description}"),
                TimeElapsedColumn(),
                console=console,
            ) as progress:
                result = await self._execute_plan(plan, progress, interactive, plan_id, store)
        else:
            result = await self._execute_plan(plan, None, interactive, plan_id, store)

        result.plan_id = plan_id

        result.total_duration_ms = (time.monotonic() - start_time) * 1000

        # Record metrics
        metrics = get_metrics()
        total_findings = len(result.all_findings)
        metrics.record_scan(
            duration=result.total_duration_ms / 1000,
            successful=result.success,
            findings_count=total_findings,
        )

        if persist_workflow and plan_id:
            assert store is not None
            store.update_plan_status(
                plan_id,
                status="completed" if result.success else "failed",
                completed=True,
            )

        # Phase 3: Summary
        if interactive:
            self._display_summary(result)

        return result

    async def resume(self, plan_id: str, interactive: bool = True) -> EngineResult:
        """Resume a previously persisted execution plan."""
        store = self._get_offline_store()
        plan_record = store.get_plan(plan_id)
        if not plan_record:
            raise ValueError(f"Plan not found: {plan_id}")

        plan_data = json.loads(plan_record.get("plan_json", "{}"))
        plan = self._plan_from_dict(plan_data)

        # Preload completed steps
        self._completed_steps.clear()
        for row in plan_record.get("steps", []):
            findings = json.loads(row.get("findings_json") or "[]")
            sr = StepResult(
                step_id=row.get("step_id", ""),
                status=StepStatus(row.get("status", StepStatus.FAILED.value)),
                output=row.get("output", "") or "",
                error=row.get("error", "") or "",
                duration_ms=float(row.get("duration_ms") or 0.0),
                findings=findings,
                retry_count=int(row.get("retry_count") or 0),
                exit_code=row.get("exit_code"),
            )
            self._completed_steps[sr.step_id] = sr

        start_time = time.monotonic()
        store.update_plan_status(plan_id, status="running")
        if interactive:
            with Progress(
                SpinnerColumn(),
                TextColumn("[bold cyan]{task.description}"),
                TimeElapsedColumn(),
                console=console,
            ) as progress:
                result = await self._execute_plan(plan, progress, interactive, plan_id, store)
        else:
            result = await self._execute_plan(plan, None, interactive, plan_id, store)
        result.total_duration_ms = (time.monotonic() - start_time) * 1000
        result.plan_id = plan_id

        # Record metrics
        metrics = get_metrics()
        metrics.record_scan(
            duration=result.total_duration_ms / 1000,
            successful=result.success,
            findings_count=len(result.all_findings),
        )

        store.update_plan_status(
            plan_id,
            status="completed" if result.success else "failed",
            completed=True,
        )

        if interactive:
            self._display_summary(result)

        return result

    def _plan_from_dict(self, data: dict[str, Any]) -> ExecutionPlan:
        """Reconstruct an ExecutionPlan from stored JSON data."""
        steps: list[ExecutionStep] = []
        for s in data.get("steps", []):
            step_type_value = s.get("step_type", StepType.TOOL_RUN.value)
            try:
                step_type = StepType(step_type_value)
            except ValueError:
                step_type = StepType.TOOL_RUN
            steps.append(
                ExecutionStep(
                    id=s.get("id", ""),
                    step_type=step_type,
                    tool=s.get("tool"),
                    command=s.get("command"),
                    args=s.get("args", []) or [],
                    target=s.get("target"),
                    depends_on=s.get("depends_on", []) or [],
                    condition=s.get("condition"),
                    timeout=int(s.get("timeout", 300)),
                    description=s.get("description", ""),
                    metadata=s.get("metadata", {}) or {},
                )
            )

        return ExecutionPlan(
            steps=steps,
            source=data.get("source", "registry"),
            confidence=float(data.get("confidence", 0.0)),
            raw_instruction=data.get("raw_instruction", ""),
            interpreted_task=None,
        )

    async def _execute_plan(
        self,
        plan: ExecutionPlan,
        progress: Progress | None,
        interactive: bool,
        plan_id: str | None,
        store: OfflineStore | None,
    ) -> EngineResult:
        """Execute all steps in the plan respecting dependencies."""
        result = EngineResult(plan=plan, mode=self._mode)

        for step in plan.steps:
            # Skip steps already completed (resume support)
            if step.id in self._completed_steps:
                sr = self._completed_steps[step.id]
                result.step_results.append(sr)
                result.all_findings.extend(sr.findings)
                result.retries_performed += sr.retry_count
                continue
            # Check dependencies
            if not self._check_dependencies(step):
                sr = StepResult(
                    step_id=step.id,
                    status=StepStatus.SKIPPED,
                    output="Skipped: dependency not met",
                )
                result.step_results.append(sr)
                self._completed_steps[step.id] = sr
                if store and plan_id:
                    store.upsert_step_execution(
                        plan_id=plan_id,
                        step_id=step.id,
                        status=sr.status.value,
                        output=sr.output[:5000],
                        error=sr.error[:2000],
                        findings=sr.findings,
                        duration_ms=sr.duration_ms,
                        retry_count=sr.retry_count,
                        exit_code=sr.exit_code,
                    )
                continue

            # Check condition
            if step.condition and not self._evaluate_condition(step.condition):
                sr = StepResult(
                    step_id=step.id,
                    status=StepStatus.SKIPPED,
                    output=f"Skipped: condition not met ({step.condition})",
                )
                result.step_results.append(sr)
                self._completed_steps[step.id] = sr
                if store and plan_id:
                    store.upsert_step_execution(
                        plan_id=plan_id,
                        step_id=step.id,
                        status=sr.status.value,
                        output=sr.output[:5000],
                        error=sr.error[:2000],
                        findings=sr.findings,
                        duration_ms=sr.duration_ms,
                        retry_count=sr.retry_count,
                        exit_code=sr.exit_code,
                    )
                continue

            # Execute the step with automatic retry on transient failures
            task_id = None
            if progress:
                task_id = progress.add_task(
                    f"[{step.id}] {step.description or step.tool or 'executing'}",
                    total=None,
                )

            sr = await self._execute_step_with_retry(step, interactive)
            result.step_results.append(sr)
            result.all_findings.extend(sr.findings)
            result.retries_performed += sr.retry_count
            self._completed_steps[step.id] = sr
            if store and plan_id:
                store.upsert_step_execution(
                    plan_id=plan_id,
                    step_id=step.id,
                    status=sr.status.value,
                    output=sr.output[:5000],
                    error=sr.error[:2000],
                    findings=sr.findings,
                    duration_ms=sr.duration_ms,
                    retry_count=sr.retry_count,
                    exit_code=sr.exit_code,
                )

            if progress and task_id is not None:
                status_icon = "✅" if sr.status == StepStatus.SUCCESS else "❌"
                progress.update(
                    task_id,
                    description=f"{status_icon} [{step.id}] {step.description}",
                    completed=True,
                )

        return result

    async def _calculate_backoff_delay(self, attempt: int) -> float:
        """Calculate exponential backoff delay with jitter."""
        delay = _RETRY_BASE_DELAY * (_RETRY_BACKOFF_FACTOR**attempt)
        delay = min(delay, _RETRY_MAX_DELAY)  # Cap maximum delay
        # Add jitter (±10%)
        import random

        jitter = delay * random.uniform(0.9, 1.1)
        return jitter

    async def _execute_step_with_retry(self, step: ExecutionStep, interactive: bool) -> StepResult:
        """Execute a step with automatic retry on transient failures."""
        retry_count = 0
        last_error = None

        # Don't retry certain step types
        no_retry_types = {StepType.REPORT, StepType.ANALYSIS}
        if step.step_type in no_retry_types:
            return await self._execute_step(step, interactive)

        while retry_count <= _MAX_RETRIES:
            try:
                result = await self._execute_step(step, interactive)

                # Success - return immediately
                if result.status == StepStatus.SUCCESS:
                    result.retry_count = retry_count
                    return result

                # Failure - check if retryable
                if result.status == StepStatus.FAILED and retry_count < _MAX_RETRIES:
                    last_error = result.error
                    # Check if error is transient (retryable)
                    if self._is_transient_error(result.error):
                        retry_count += 1
                        delay = await self._calculate_backoff_delay(retry_count - 1)
                        logger.warning(
                            "Step %s failed (retryable): %s. Retrying in %.1fs (attempt %d/%d)",
                            step.id,
                            result.error,
                            delay,
                            retry_count,
                            _MAX_RETRIES,
                        )
                        await asyncio.sleep(delay)
                        continue

                # Non-retryable or final attempt
                result.retry_count = retry_count
                return result

            except Exception as e:
                last_error = str(e)
                if retry_count < _MAX_RETRIES and self._is_transient_error(last_error):
                    retry_count += 1
                    delay = await self._calculate_backoff_delay(retry_count - 1)
                    logger.warning(
                        "Step %s raised exception (retryable): %s. Retrying in %.1fs (attempt %d/%d)",
                        step.id,
                        str(e),
                        delay,
                        retry_count,
                        _MAX_RETRIES,
                    )
                    await asyncio.sleep(delay)
                    continue
                else:
                    # Non-retryable exception or max retries exceeded
                    return StepResult(
                        step_id=step.id,
                        status=StepStatus.FAILED,
                        error=last_error or str(e),
                        retry_count=retry_count,
                    )

        # Max retries exceeded
        return StepResult(
            step_id=step.id,
            status=StepStatus.FAILED,
            error=f"Max retries ({_MAX_RETRIES}) exceeded: {last_error}",
            retry_count=retry_count,
        )

    def _is_transient_error(self, error: str) -> bool:
        """Check if error is transient and retryable."""
        transient_indicators = [
            "timeout",
            "temporarily unavailable",
            "connection refused",
            "connection reset",
            "connection timeout",
            "temporarily",
            "busy",
            "try again",
            "server is unavailable",
            "gateway timeout",
            "internal server error",
        ]

        error_lower = str(error).lower()
        return any(indicator in error_lower for indicator in transient_indicators)

    async def _execute_step(self, step: ExecutionStep, interactive: bool) -> StepResult:
        """Execute a single step based on its type."""
        start = time.monotonic()

        try:
            if step.step_type == StepType.TOOL_RUN:
                return await self._run_tool_step(step, interactive)
            elif step.step_type == StepType.SHELL_CMD:
                return await self._run_shell_step(step, interactive)
            elif step.step_type == StepType.ANALYSIS:
                return await self._run_analysis_step(step)
            elif step.step_type == StepType.REPORT:
                return self._run_report_step(step)
            elif step.step_type == StepType.PARALLEL_GROUP:
                return await self._run_parallel_step(step, interactive)
            else:
                return StepResult(
                    step_id=step.id,
                    status=StepStatus.SKIPPED,
                    output=f"Unsupported step type: {step.step_type}",
                )
        except Exception as exc:
            duration = (time.monotonic() - start) * 1000
            logger.exception("Step %s failed", step.id)
            return StepResult(
                step_id=step.id,
                status=StepStatus.FAILED,
                error=str(exc),
                duration_ms=duration,
            )

    async def _run_tool_step(self, step: ExecutionStep, interactive: bool) -> StepResult:
        """Execute a registered security tool."""
        tool_name = step.tool or ""
        start = time.monotonic()

        # Handle "__all__" special case
        if tool_name == "__all__":
            findings: list[dict[str, Any]] = []
            outputs: list[str] = []
            metrics = get_metrics()
            for tool_info in self._discovered_tools:
                tool_start = time.monotonic()
                args = list(step.args)
                if step.target:
                    args.append(step.target)
                result = await run_tool_complete(tool_info.path, args, step.timeout)
                tool_duration = time.monotonic() - tool_start
                outputs.append(f"--- {tool_info.name} ---\n{result.stdout}")
                # Parse findings if parser available
                tool_findings = self._parse_tool_output(tool_info.name, result.stdout)
                findings.extend(tool_findings)
                metrics.record_tool_execution(
                    tool_name=tool_info.name,
                    duration=tool_duration,
                    successful=result.exit_code == 0,
                    findings_count=len(tool_findings),
                )
            duration = (time.monotonic() - start) * 1000

            return StepResult(
                step_id=step.id,
                status=StepStatus.SUCCESS,
                output="\n".join(outputs),
                duration_ms=duration,
                findings=findings,
            )

        # Resolve the tool
        resolved = self._resolver.resolve(tool_name, step.args)

        if not resolved.is_safe:
            if interactive:
                console.print(
                    f"[red]⚠ Blocked unsafe command:[/red] {tool_name}\n"
                    f"  Reasons: {'; '.join(resolved.warnings)}"
                )
            return StepResult(
                step_id=step.id,
                status=StepStatus.BLOCKED,
                error=f"Blocked: {'; '.join(resolved.warnings)}",
            )

        # Build args
        args = list(step.args)
        if step.target:
            args.append(step.target)

        # Execute
        result = await run_tool_complete(resolved.path, args, step.timeout)
        duration = (time.monotonic() - start) * 1000

        # Parse findings
        findings = self._parse_tool_output(tool_name, result.stdout)

        # Record tool execution metrics
        get_metrics().record_tool_execution(
            tool_name=tool_name,
            duration=duration / 1000,
            successful=result.exit_code == 0,
            findings_count=len(findings),
        )

        return StepResult(
            step_id=step.id,
            status=StepStatus.SUCCESS if result.exit_code == 0 else StepStatus.FAILED,
            output=result.stdout,
            error=result.stderr if result.exit_code != 0 else "",
            duration_ms=duration,
            findings=findings,
        )

    async def _run_shell_step(self, step: ExecutionStep, interactive: bool) -> StepResult:
        """Execute a shell command (from autonomous model planning)."""
        command = step.command or ""
        if not command:
            return StepResult(
                step_id=step.id,
                status=StepStatus.SKIPPED,
                output="No command specified",
            )

        # Resolve and validate
        parts = command.split()
        base_cmd = parts[0]
        args = parts[1:] + list(step.args)
        if step.target:
            args.append(step.target)

        resolved = self._resolver.resolve(base_cmd, args)

        if not resolved.is_safe:
            if interactive:
                console.print(
                    f"[red]⚠ Blocked unsafe command:[/red] {command}\n"
                    f"  Reasons: {'; '.join(resolved.warnings)}"
                )
            return StepResult(
                step_id=step.id,
                status=StepStatus.BLOCKED,
                error=f"Blocked: {'; '.join(resolved.warnings)}",
            )

        # Warn for unregistered commands
        if resolved.warnings and interactive:
            for w in resolved.warnings:
                console.print(f"[yellow]⚠ {w}[/yellow]")

        start = time.monotonic()
        result = await run_tool_complete(resolved.path, resolved.args, step.timeout)
        duration = (time.monotonic() - start) * 1000

        return StepResult(
            step_id=step.id,
            status=StepStatus.SUCCESS if result.exit_code == 0 else StepStatus.FAILED,
            output=result.stdout,
            error=result.stderr if result.exit_code != 0 else "",
            duration_ms=duration,
        )

    async def _run_analysis_step(self, step: ExecutionStep) -> StepResult:
        """Run a model-driven analysis step on previous results."""
        # Gather outputs from previous steps
        context_outputs = []
        for dep_id in step.depends_on:
            dep_result = self._completed_steps.get(dep_id)
            if dep_result and dep_result.output:
                context_outputs.append(
                    f"[{dep_id}] {dep_result.output[:_MAX_CONTEXT_OUTPUT_LENGTH]}"
                )

        # For now, provide a structured summary
        summary = f"Analysis requested. Context from {len(context_outputs)} previous step(s)."
        if context_outputs:
            summary += "\n" + "\n".join(context_outputs[:5])

        return StepResult(
            step_id=step.id,
            status=StepStatus.SUCCESS,
            output=summary,
            metadata={"type": "analysis", "context_count": len(context_outputs)},
        )

    def _run_report_step(self, step: ExecutionStep) -> StepResult:
        """Generate a report step."""
        fmt = step.metadata.get("format", "text")
        return StepResult(
            step_id=step.id,
            status=StepStatus.SUCCESS,
            output=f"Report generation ({fmt}) — delegated to report engine",
            metadata={"format": fmt},
        )

    async def _run_parallel_step(self, step: ExecutionStep, interactive: bool) -> StepResult:
        """Execute a group of steps in parallel with concurrency control."""
        sub_steps = step.metadata.get("steps", [])
        max_concurrent = step.metadata.get("max_concurrent", 3)

        if not sub_steps:
            return StepResult(step_id=step.id, status=StepStatus.SKIPPED, output="No sub-steps")

        # Create semaphore for concurrency limit
        semaphore = asyncio.Semaphore(max_concurrent)
        start = time.monotonic()

        async def run_bounded(s: ExecutionStep) -> StepResult:
            """Run step with bounded concurrency."""
            async with semaphore:
                return await self._execute_step_with_retry(s, interactive)

        # Execute all steps concurrently
        tasks = [run_bounded(s) for s in sub_steps]
        results = await asyncio.gather(*tasks, return_exceptions=True)

        # Aggregate results
        all_findings = []
        all_outputs = []
        all_errors = []
        total_retries = 0

        for res in results:
            if isinstance(res, Exception):
                all_errors.append(str(res))
                logger.error("Parallel step failed with exception: %s", res)
            elif isinstance(res, StepResult):
                all_findings.extend(res.findings)
                if res.output:
                    all_outputs.append(f"[{res.step_id}] {res.output}")
                if res.error:
                    all_errors.append(f"[{res.step_id}] {res.error}")
                total_retries += res.retry_count

                # Track individual step in completed
                self._completed_steps[res.step_id] = res

        duration_ms = (time.monotonic() - start) * 1000

        return StepResult(
            step_id=step.id,
            status=StepStatus.SUCCESS if not all_errors else StepStatus.FAILED,
            output="\n".join(all_outputs) if all_outputs else "Parallel execution completed",
            error="; ".join(all_errors) if all_errors else "",
            findings=all_findings,
            duration_ms=duration_ms,
            retry_count=total_retries,
        )

    def _check_dependencies(self, step: ExecutionStep) -> bool:
        """Check if all dependencies have completed successfully."""
        for dep_id in step.depends_on:
            dep_result = self._completed_steps.get(dep_id)
            if dep_result is None:
                return False
            if dep_result.status not in (StepStatus.SUCCESS, StepStatus.SKIPPED):
                return False
        return True

    def _evaluate_condition(self, condition: str) -> bool:
        """Evaluate a step condition based on completed steps."""
        # Simple condition evaluation
        if "findings.count > 0" in condition:
            total_findings = sum(len(r.findings) for r in self._completed_steps.values())
            return total_findings > 0
        return True  # Default: execute

    def _parse_tool_output(self, tool_name: str, output: str) -> list[dict[str, Any]]:
        """Parse tool output using registered parsers."""
        from .parsers import GobusterParser, NiktoParser, NmapParser, NucleiParser

        parsers: dict[str, Any] = {
            "nmap": NmapParser(),
            "nikto": NiktoParser(),
            "nuclei": NucleiParser(),
            "gobuster": GobusterParser(),
        }

        parser = parsers.get(tool_name)
        if parser:
            try:
                return parser.parse(output)
            except Exception as exc:
                logger.warning("Parser for %s failed: %s", tool_name, exc)

        return []

    # ------------------------------------------------------------------
    # Display helpers
    # ------------------------------------------------------------------

    def _display_plan(self, plan: ExecutionPlan) -> None:
        """Display the execution plan to the user."""
        source_colors = {
            "registry": "blue",
            "autonomous": "green",
            "integrated-registry": "cyan",
            "integrated-autonomous": "magenta",
            "integrated-fallback": "yellow",
        }
        color = source_colors.get(plan.source, "white")

        table = Table(
            title=f"Execution Plan [{plan.source}]",
            show_header=True,
            header_style="bold",
        )
        table.add_column("#", style="dim", width=4)
        table.add_column("Type", style="cyan", width=12)
        table.add_column("Tool/Command", style="bold")
        table.add_column("Target", style="green")
        table.add_column("Description")

        for i, step in enumerate(plan.steps, 1):
            tool_cmd = step.tool or step.command or "—"
            table.add_row(
                str(i),
                step.step_type.value,
                tool_cmd,
                step.target or "—",
                step.description,
            )

        console.print()
        console.print(
            Panel(
                table,
                title=f"[{color}]🚀 Execution Engine — {plan.source.upper()} mode[/{color}]",
                subtitle=f"Confidence: {plan.confidence:.0%}",
            )
        )
        console.print()

    def _display_summary(self, result: EngineResult) -> None:
        """Display the execution summary."""
        status_icons = {
            "success": "✅",
            "failed": "❌",
            "skipped": "⏭️",
            "blocked": "🚫",
        }

        console.print()
        lines = [
            f"[bold]Execution Summary[/bold] ({result.mode.value} mode)",
            f"  Duration: {result.total_duration_ms / 1000:.1f}s",
            f"  Steps: {len(result.step_results)}",
        ]

        for status, count in result.summary.items():
            icon = status_icons.get(status, "•")
            lines.append(f"  {icon} {status}: {count}")

        if result.all_findings:
            lines.append(f"  📋 Total findings: {len(result.all_findings)}")

        console.print(
            Panel(
                "\n".join(lines),
                title="[bold green]✨ Complete[/bold green]"
                if result.success
                else "[bold red]⚠ Issues[/bold red]",
            )
        )
