# SPDX-License-Identifier: AGPL-3.0-or-later
"""Autonomous executor — executes raw shell commands generated by the LLM with streaming output."""

from __future__ import annotations

import asyncio
import logging
import os
import time as _time
from dataclasses import dataclass, field
from typing import Any

from .events import Event, EventType
from .exceptions import ToolExecutionError, ToolNotFoundError
from .executor import BaseExecutor
from .models import ExecutionPlan, PlanStep, PlanStatus, StepStatus

logger = logging.getLogger(__name__)


@dataclass
class CommandResult:
    label: str
    lines: list[str] = field(default_factory=list)
    exit_code: int | None = None
    done: bool = False
    output: str = ""
    error: str = ""


class AutonomousExecutor(BaseExecutor):
    """Executes raw shell commands from the LLM with live streaming output.

    Falls back to ToolRegistry for non-command steps and attempts to parse
    shell output through the parser registry when the tool name is known.
    """

    def __init__(
        self,
        max_workers: int = 10,
        permission_gate: Any = None,
        command_review: bool = True,
        registry: Any = None,
    ) -> None:
        super().__init__(max_workers=max_workers, permission_gate=permission_gate)
        self._command_review = command_review
        self._custom_handlers: dict[str, Any] = {}
        self._registry = registry

    @property
    def command_review(self) -> bool:
        return self._command_review

    @command_review.setter
    def command_review(self, value: bool) -> None:
        self._command_review = value

    async def execute_plan(
        self,
        plan: ExecutionPlan,
        executor_fn: Any = None,
        live_display: bool = True,
    ) -> ExecutionPlan:
        """Execute all steps in *plan* as shell commands with optional live streaming.

        Parameters
        ----------
        plan:
            The execution plan with command-based steps.
        executor_fn:
            Optional custom step executor override.
        live_display:
            Whether to show live streaming output (default: True).
        """
        self._budget.reset_timer()
        plan.status = PlanStatus.ACTIVE

        await self._event_bus.emit(
            Event(
                type=EventType.PLAN_CREATED,
                source="executor_autonomous",
                data={"plan_id": plan.id, "goal": plan.goal, "steps": len(plan.steps)},
            )
        )

        # Pre-review all shell commands
        if self._command_review:
            approved = await self._review_commands(plan)
            if not approved:
                plan.status = PlanStatus.CANCELLED
                return plan

        cmd_states = self._build_cmd_states(plan)
        exec_tasks = [self._exec_one(s, st) for s, st in zip(plan.steps, cmd_states)]

        if live_display and cmd_states:
            plan = await self._execute_with_live_display(plan, exec_tasks, cmd_states)
        else:
            plan = await self._execute_batch(plan, exec_tasks, cmd_states)

        plan.status = PlanStatus.COMPLETED if not plan.has_failures else PlanStatus.FAILED
        await self._event_bus.emit(
            Event(
                type=EventType.PLAN_COMPLETE,
                source="executor_autonomous",
                data={
                    "plan_id": plan.id,
                    "status": plan.status.value,
                    "progress": plan.progress_pct,
                },
            )
        )
        return plan

    async def _review_commands(self, plan: ExecutionPlan) -> bool:
        """Review all shell commands via the confirmation gate."""
        from .shell_review import review_and_confirm

        for s in plan.steps:
            if not s.command:
                continue
            reviewed = review_and_confirm(
                s.command, "raw", "Raw shell command from LLM-generated plan"
            )
            if reviewed is None:
                logger.warning("Command cancelled by user: %s", s.command[:60])
                return False
            s.command = reviewed
        return True

    def _build_cmd_states(self, plan: ExecutionPlan) -> list[CommandResult]:
        states = []
        for s in plan.steps:
            if s.command:
                states.append(CommandResult(label=f"$ {s.command}"))
            elif s.tool and s.tool not in ("execute_plan", "_", ""):
                states.append(CommandResult(label=s.tool))
            else:
                states.append(CommandResult(label="(no command)"))
        return states

    async def _exec_one(
        self, step: PlanStep, state: CommandResult
    ) -> tuple[PlanStep, dict[str, Any]]:
        """Execute a single plan step and capture output."""
        if not self._budget.consume_iteration():
            return step, {"status": "error", "error": "Budget exhausted"}

        step.status = StepStatus.RUNNING
        await self._event_bus.emit(
            Event(
                type=EventType.PLAN_STEP_START,
                source="executor_autonomous",
                data={"step_id": step.id, "tool": step.tool or "shell"},
            )
        )

        if self._on_step_progress:
            self._on_step_progress(step)

        self.normalise_step(step)

        from siyarix.stealth import stealth_engine
        if stealth_engine.config.enabled:
            delay = stealth_engine.get_randomized_delay(1.0)
            if delay > 0:
                await asyncio.sleep(delay)

        start = _time.monotonic()
        try:
            if not step.command:
                # No shell command — likely a tool name with args
                result = await self._execute_tool_step(step)
                state.exit_code = 0 if result.get("status") == "success" else 1
                out = (result.get("output") or "").strip()
                err = (result.get("error") or "").strip()
                if out:
                    state.lines.extend(out.split("\n"))
                    state.output = out
                if err:
                    state.lines.extend(err.split("\n"))
                    state.error = err
            else:
                result = await self._execute_shell_command(step, state)
                # Parse shell command output through the tool's parser when available
                result = self._try_parse_output(step, result)

            step.duration_ms = (_time.monotonic() - start) * 1000
            step.result = result

            success = result.get("status") == "success"
            step.status = StepStatus.COMPLETED if success else StepStatus.FAILED
            self._tracker.record(step.tool or "shell", step.command or str(step.args), success)
            state.done = True

            if success:
                await self._event_bus.emit(
                    Event(
                        type=EventType.PLAN_STEP_COMPLETE,
                        source="executor_autonomous",
                        data={"step_id": step.id, "duration_ms": step.duration_ms},
                    )
                )
            else:
                await self._event_bus.emit(
                    Event(
                        type=EventType.PLAN_STEP_FAILED,
                        source="executor_autonomous",
                        data={"step_id": step.id, "error": result.get("error", "")},
                    )
                )

        except Exception as e:
            step.duration_ms = (_time.monotonic() - start) * 1000
            step.status = StepStatus.FAILED
            step.result = {"status": "error", "error": str(e)}
            state.exit_code = -1
            state.done = True
            self._tracker.record(step.tool or "shell", step.command or str(step.args), False)

        if self._on_step_progress:
            self._on_step_progress(step)

        return step, step.result

    async def _execute_tool_step(self, step: PlanStep) -> dict[str, Any]:
        """Execute a step that has a tool name but no shell command."""
        handler = self._custom_handlers.get(step.tool)
        if handler:
            return await handler(step)
        if self._registry:
            try:
                result = await self._registry.execute(step.tool, **step.args)
                return self._try_parse_output(step, result)
            except (ToolNotFoundError, ToolExecutionError) as e:
                return {"status": "error", "error": str(e), "tool": step.tool}
        return {
            "status": "error",
            "error": f"LLM generated step for tool '{step.tool}' without a raw shell command. Autonomous mode requires a 'command' field for execution.",
        }

    async def _execute_shell_command(self, step: PlanStep, state: CommandResult) -> dict[str, Any]:
        """Execute a shell command with subprocess."""
        from .subprocess_utils import get_platform_shell_cmd, safe_run_async_stream

        cmd_timeout = int(step.timeout or 300)

        exec_result = await safe_run_async_stream(
            get_platform_shell_cmd(step.command or ""),
            timeout=cmd_timeout,
            validate=False,
            on_stdout=lambda line: state.lines.append(line),
            on_stderr=lambda line: state.lines.append(line),
        )

        state.exit_code = exec_result.exit_code
        state.output = exec_result.stdout
        state.error = exec_result.stderr
        state.done = True

        return {
            "status": "success" if not exec_result.exit_code else "error",
            "output": exec_result.stdout,
            "error": exec_result.stderr,
            "exit_code": exec_result.exit_code,
        }

    async def _execute_with_live_display(
        self,
        plan: ExecutionPlan,
        exec_tasks: list[Any],
        cmd_states: list[CommandResult],
    ) -> ExecutionPlan:
        """Execute with rich live display showing streaming output."""
        exec_task = asyncio.ensure_future(asyncio.gather(*exec_tasks))

        from rich.live import Live
        from rich.panel import Panel as RichPanel

        _old_term = os.environ.get("TERM")
        os.environ["TERM"] = "xterm-256color"

        if cmd_states:
            focus_idx = 0
            done_set = False
            wave_start = _time.time()

            with Live(refresh_per_second=10, screen=False) as live:
                while not done_set:
                    await asyncio.sleep(0.1)
                    if cmd_states[focus_idx].done:
                        unfinished = [i for i, st in enumerate(cmd_states) if not st.done]
                        if unfinished:
                            focus_idx = unfinished[0]
                        else:
                            done_set = True

                    st = cmd_states[focus_idx]
                    elapsed = _time.time() - wave_start
                    icon = "·" if st.exit_code is None else ("✓" if not st.exit_code else "✗")
                    border = (
                        "cyan" if st.exit_code is None else ("green" if not st.exit_code else "red")
                    )

                    panel_content = (
                        "\n".join(st.lines[-200:])
                        if st.lines
                        else (
                            f"Running... ({elapsed:.1f}s)"
                            if st.exit_code is None
                            else "(no output)"
                        )
                    )

                    live.update(
                        RichPanel(
                            panel_content,
                            title=f"{icon} {st.label}",
                            subtitle=f"Elapsed: {elapsed:.1f}s" if st.exit_code is None else None,
                            border_style=border,
                        )
                    )

        raw_results = await exec_task

        if _old_term is not None:
            os.environ["TERM"] = _old_term
        else:
            os.environ.pop("TERM", None)

        # Update plan step statuses from results
        for step, result in raw_results:
            for s in plan.steps:
                if s.id == step.id:
                    s.status = step.status
                    s.result = result
                    s.duration_ms = step.duration_ms
                    break

        return plan

    async def _execute_batch(
        self,
        plan: ExecutionPlan,
        exec_tasks: list[Any],
        cmd_states: list[CommandResult],
    ) -> ExecutionPlan:
        """Execute steps without live display (simple batch mode)."""
        raw_results = await asyncio.gather(*exec_tasks, return_exceptions=True)
        for i, result in enumerate(raw_results):
            if isinstance(result, BaseException):
                logger.error("Step execution exception: %s", result, exc_info=result)
                continue
            step, step_result = result
            for s in plan.steps:
                if s.id == step.id:
                    s.status = step.status
                    s.result = step_result
                    s.duration_ms = step.duration_ms
                    break
        return plan

    def register_handler(self, name: str, handler: Any) -> None:
        """Register a custom handler for non-command tool steps."""
        self._custom_handlers[name] = handler

    # ── Step normalisation ─────────────────────────────────────────────────

    def normalise_step(self, step: PlanStep) -> None:
        """Validate and normalise a plan step before execution.

        - Extracts tool name from command when tool is empty
        - Populates args from command content when args are empty
        - Marks step origin in metadata
        """
        if not step.tool and step.command:
            first_word = step.command.strip().split()[0] if step.command.strip() else ""
            if first_word:
                step.tool = first_word

        if step.tool and not step.args and step.command:
            parts = step.command.strip().split()
            if len(parts) > 1:
                non_flag_args = [p for p in parts[1:] if not p.startswith("-")]
                if non_flag_args:
                    step.args["target"] = non_flag_args[-1]
                flag_parts = [p for p in parts[1:] if p.startswith("-")]
                if flag_parts:
                    step.args["flags"] = " ".join(flag_parts)

        step.metadata.setdefault("origin", "autonomous")

    def _try_parse_output(self, step: PlanStep, result: dict[str, Any]) -> dict[str, Any]:
        """Run the parser registry on shell-command output when the tool is known."""
        if not step.tool or not self._registry:
            return result
        parser_registry = getattr(self._registry, "_parser_registry", None)
        if not parser_registry or not hasattr(parser_registry, "has_parser"):
            return result
        if not parser_registry.has_parser(step.tool):
            return result
        output = (result.get("output") or "").strip()
        if not output:
            return result
        try:
            parsed = parser_registry.parse(step.tool, output)
            if parsed:
                result["findings"] = parsed
        except Exception:
            logger.debug("Parser failed for tool %s (output length=%d)", step.tool, len(output))
        return result


__all__ = [
    "AutonomousExecutor",
    "CommandResult",
]
