"""Execution engine — combines autonomous task planning with registry-based
tool execution.

This is the core of the execution architecture:

- **Registry mode**: Uses the tool registry directly for known tools.
- **Autonomous mode**: Model-driven planning and execution.
- **Integrated mode** (default): Model-driven planning for complex tasks with
  registry-based execution for known tools and intelligent fallback.

The engine provides a unified execution interface regardless of whether the
plan was generated by a model or from the static registry.
"""

from __future__ import annotations

import asyncio
import json
import logging
import platform
import re
import shutil
import time
import uuid
from dataclasses import dataclass, field
from enum import StrEnum
from typing import Any

from rich.console import Console
from rich.panel import Panel
from rich.progress import (Progress, SpinnerColumn, TextColumn,
                           TimeElapsedColumn)
from rich.table import Table

from .dynamic_resolver import DynamicResolver
from .engine_types import StepResult, StepStatus
from .executor import run_tool_complete
from .kill_switch import KillSwitch, KillSwitchState
from .knowledge_graph import KnowledgeGraph
from .metrics import get_metrics
from .notifications import notification_center
from .offline_store import OfflineStore
from .planner import ExecutionPlan, ExecutionStep, StepType, TaskPlanner
from .providers import registry as provider_registry
from .tool_executor import ToolExecutor
from .tool_registry import ToolInfo, ToolRegistry
from .worker_pool import AsyncWorkerPool
from .xi import ContextTracker, Predictor, SkillProfiler, XICoreService

logger = logging.getLogger(__name__)
console = Console()

# Maximum characters of output to include in model analysis context per step
_MAX_CONTEXT_OUTPUT_LENGTH = 2000

# Retry configuration
_MAX_RETRIES = 3
_RETRY_BACKOFF_FACTOR = 2.0
_RETRY_BASE_DELAY = 1.0  # seconds
_RETRY_MAX_DELAY = 30.0  # seconds


class ExecutionMode(StrEnum):
    """Execution mode for the engine."""

    REGISTRY = "registry"  # Registry-only (no model-driven planning)
    AUTONOMOUS = "autonomous"  # Model-driven planning and execution
    INTEGRATED = "integrated"  # Model-driven planning with registry fallback


@dataclass
class EngineResult:
    """Aggregate result of executing an entire plan."""

    plan: ExecutionPlan
    step_results: list[StepResult] = field(default_factory=list)
    total_duration_ms: float = 0.0
    mode: ExecutionMode = ExecutionMode.INTEGRATED
    all_findings: list[dict[str, Any]] = field(default_factory=list)
    plan_id: str | None = None  # Plan ID for persistence
    retries_performed: int = 0  # Total retries across all steps

    @property
    def success(self) -> bool:
        return all(
            r.status in (StepStatus.SUCCESS, StepStatus.SKIPPED)
            for r in self.step_results
        )

    @property
    def summary(self) -> dict[str, int]:
        counts: dict[str, int] = {}
        for r in self.step_results:
            counts[r.status.value] = counts.get(r.status.value, 0) + 1
        return counts

    def to_dict(self) -> dict[str, Any]:
        """Convert to dictionary for storage/serialization."""
        return {
            "plan_id": self.plan_id,
            "plan": self.plan.to_dict(),
            "step_results": [
                {
                    "step_id": r.step_id,
                    "status": r.status.value,
                    "output": r.output[:1000],  # Truncate for storage
                    "error": r.error,
                    "duration_ms": r.duration_ms,
                    "findings": r.findings,
                    "retry_count": r.retry_count,
                    "exit_code": r.exit_code,
                }
                for r in self.step_results
            ],
            "total_duration_ms": self.total_duration_ms,
            "mode": self.mode.value,
            "success": self.success,
            "retries_performed": self.retries_performed,
        }


class ExecutionEngine:
    """The core execution engine.

    Combines model-driven autonomous planning with registry-based execution.
    Supports three modes: registry, autonomous, and integrated (default).

    Usage::

        engine = ExecutionEngine()
        result = await engine.execute("scan 192.168.1.1 with nmap then analyze results")
    """

    def __init__(
        self,
        mode: ExecutionMode = ExecutionMode.INTEGRATED,
        registry: ToolRegistry | None = None,
        config: dict[str, Any] | None = None,
        learning_memory: Any = None,
        session_logger: Any = None,
    ) -> None:
        self._mode = mode
        self._registry = registry or ToolRegistry()
        self._config = config or {}

        # Discover tools and build context
        fast_discovery = bool(self._config.get("fast_discovery"))
        self._discovered_tools = self._registry.discover(fast=fast_discovery)
        self._tool_map: dict[str, ToolInfo] = {
            t.name: t for t in self._discovered_tools
        }
        self._binary_map: dict[str, ToolInfo] = {
            t.binary: t for t in self._discovered_tools
        }

        # Initialize task planner with providers
        self._planner = TaskPlanner()
        self._setup_providers()

        # Runtime intelligence services (XI)
        self._xi_tracker = ContextTracker()
        self._xi_predictor = Predictor()
        self._replan_attempts = 0
        self._max_replans = int(self._config.get("max_replans", 3))

        # Bounded sub-agent pool
        max_subagents = int(self._config.get("max_subagents", 15))
        self._pool = AsyncWorkerPool(max_workers=max_subagents)

        # Initialize dynamic resolver
        registered = {t.binary: t.path for t in self._discovered_tools}
        registered.update({t.name: t.path for t in self._discovered_tools})
        self._resolver = DynamicResolver(registered_tools=registered)

        # Shared graph and step state
        self._graph = KnowledgeGraph()

        # Tool executor (delegates actual tool/shell runs)
        self._executor = ToolExecutor(
            resolver=self._resolver,
            discovered_tools=self._discovered_tools,
            graph=self._graph,
        )

        # Step results for tracking
        self._completed_steps: dict[str, StepResult] = {}
        self._offline_store: OfflineStore | None = None

        # Learning memory for correction tracking
        self._learning_memory = learning_memory

        # Session logger for structured audit logging
        self._session_logger = session_logger
        self._current_log_session_id: str | None = None

        # Lazy XI services (SkillProfiler & XICoreService)
        self._xi_skill_profiler: SkillProfiler | None = None
        self._xi_core_service: XICoreService | None = None

        # Kill switch for emergency stop
        self._kill_switch = KillSwitch()
        self._kill_switch.register(self._on_kill)

    @property
    def kill_switch(self) -> KillSwitch:
        return self._kill_switch

    def _on_kill(self) -> None:
        """Callback when kill switch is triggered."""
        logger.warning("Kill switch triggered - cancelling all pool tasks")
        try:
            self._pool.cancel_pending()
        except Exception as exc:
            logger.exception("Pool cancellation failed: %s", exc)

    def _get_offline_store(self) -> OfflineStore:
        """Get or create offline store instance."""
        if self._offline_store is None:
            self._offline_store = OfflineStore()
        return self._offline_store

    def _get_skill_profiler(self) -> SkillProfiler:
        if self._xi_skill_profiler is None:
            self._xi_skill_profiler = SkillProfiler()
        return self._xi_skill_profiler

    def _get_xi_core_service(self) -> XICoreService:
        if self._xi_core_service is None:
            self._xi_core_service = XICoreService()
        return self._xi_core_service

    def _refresh_tools(self) -> None:
        """Force rediscovery of installed tools and rebuild the resolver."""
        fast_discovery = bool(self._config.get("fast_discovery"))
        self._discovered_tools = self._registry.discover(
            force_refresh=True, fast=fast_discovery
        )
        self._tool_map = {t.name: t for t in self._discovered_tools}
        self._binary_map = {t.binary: t for t in self._discovered_tools}

        registered = {t.binary: t.path for t in self._discovered_tools}
        registered.update({t.name: t.path for t in self._discovered_tools})
        self._resolver = DynamicResolver(registered_tools=registered)

    async def _try_install_tool(self, tool_name: str) -> bool:
        """Attempt to automatically install a required tool after obtaining user permission."""
        system = platform.system().lower()
        package_names = {
            "nmap": "nmap",
            "masscan": "masscan",
            "amass": "amass",
            "subfinder": "subfinder",
            "dnsx": "dnsx",
            "theHarvester": "theharvester",
            "whois": "whois",
            "shodan": "shodan",
            "nikto": "nikto",
            "gobuster": "gobuster",
            "ffuf": "ffuf",
            "feroxbuster": "feroxbuster",
            "httpx": "httpx",
            "wpscan": "wpscan",
            "sqlmap": "sqlmap",
            "nuclei": "nuclei",
            "hydra": "hydra",
            "john": "john",
            "hashcat": "hashcat",
            "msfconsole": "metasploit-framework",
            "trufflehog": "trufflehog",
            "gitleaks": "gitleaks",
            "aws": "awscli",
            "az": "azure-cli",
            "gcloud": "google-cloud-sdk",
            "docker": "docker",
            "podman": "podman",
            "kubectl": "kubernetes-cli",
            "helm": "helm",
            "terraform": "terraform",
            "ansible": "ansible",
            "uv": "uv",
        }

        package = package_names.get(tool_name, tool_name)
        install_commands: list[list[str]] = []

        python_tools = {"shodan", "trufflehog", "ansible", "theHarvester"}
        if tool_name in python_tools or package == "shodan":
            install_commands.append(["pip", "install", "--upgrade", package])
            install_commands.append(["pip3", "install", "--upgrade", package])
            install_commands.append(
                ["python", "-m", "pip", "install", "--upgrade", package]
            )
            install_commands.append(
                ["python3", "-m", "pip", "install", "--upgrade", package]
            )

        if system == "windows":
            install_commands.append(
                [
                    "winget",
                    "install",
                    "-e",
                    "--id",
                    (
                        f"SecurityTool.{package}"
                        if package in ["nmap", "wireshark"]
                        else package
                    ),
                    "--silent",
                    "--accept-package-agreements",
                    "--accept-source-agreements",
                ]
            )
            install_commands.append(["winget", "install", package, "--silent"])
            install_commands.append(
                ["choco", "install", package, "-y", "--no-progress"]
            )
        elif system == "darwin":
            install_commands.append(["brew", "install", package])
        else:  # Linux (Debian, Ubuntu, Kali, etc.)
            install_commands.append(["sudo", "apt-get", "update", "-y"])
            install_commands.append(["sudo", "apt-get", "install", "-y", package])
            install_commands.append(["apt-get", "install", "-y", package])

        from .output import output

        valid_installers = []
        for cmd in install_commands:
            installer_bin = cmd[0]
            if shutil.which(installer_bin):
                valid_installers.append(cmd)

        if not valid_installers:
            console.print(
                f"[yellow]⚠ Cannot automatically install '{tool_name}': No package manager (winget/choco/brew/apt/pip) found on PATH.[/yellow]"
            )
            return False

        installer_desc = " / ".join([" ".join(c) for c in valid_installers[:2]])
        confirm_msg = f"Tool '{tool_name}' is required but not installed. Do you want to automatically install it? (Proposed: {installer_desc})"

        if not output.prompt_confirm(confirm_msg, default=True):
            console.print(
                f"[yellow]✗ Skipping installation of '{tool_name}' by user request.[/yellow]"
            )
            return False

        console.print(
            f"[bold blue]⚡ Initiating auto-installation of '{tool_name}'...[/bold blue]"
        )

        success = False
        for cmd in valid_installers:
            console.print(f"[dim]Running: {' '.join(cmd)}[/dim]")
            try:
                result = await run_tool_complete(cmd[0], cmd[1:], timeout=300)
                if result.exit_code == 0:
                    success = True
                    console.print(
                        f"[bold green]✓ Successfully installed '{tool_name}' via '{cmd[0]}'![/bold green]"
                    )
                    break
                else:
                    console.print(
                        f"[yellow]⚠ Installer '{cmd[0]}' exited with code {result.exit_code}. Trying next installer...[/yellow]"
                    )
            except Exception as e:
                console.print(
                    f"[dim]Installer '{cmd[0]}' encountered an error: {e}[/dim]"
                )

        if success:
            self._refresh_tools()
            return True
        else:
            console.print(
                f"[red]✗ Failed to install '{tool_name}'. Please install it manually.[/red]"
            )
            return False

    def _setup_providers(self) -> None:
        """Configure model providers based on available configuration."""
        # Instantiate adapters from the global provider registry
        preferred = str(self._config.get("model_provider", "auto")).strip().lower()
        preference_map = {
            "gemini": [
                "gemini",
                "openai",
                "anthropic",
                "groq",
                "together",
                "ollama",
                "lmstudio",
                "cloud",
                "noop",
            ],
            "openai": [
                "openai",
                "gemini",
                "anthropic",
                "groq",
                "together",
                "ollama",
                "lmstudio",
                "cloud",
                "noop",
            ],
            "ollama": [
                "ollama",
                "lmstudio",
                "gemini",
                "openai",
                "anthropic",
                "groq",
                "together",
                "cloud",
                "noop",
            ],
            "cloud": [
                "cloud",
                "gemini",
                "openai",
                "anthropic",
                "groq",
                "together",
                "ollama",
                "lmstudio",
                "noop",
            ],
            "groq": [
                "groq",
                "openai",
                "gemini",
                "anthropic",
                "together",
                "ollama",
                "lmstudio",
                "cloud",
                "noop",
            ],
            "together": [
                "together",
                "groq",
                "openai",
                "gemini",
                "anthropic",
                "ollama",
                "lmstudio",
                "cloud",
                "noop",
            ],
            "lmstudio": [
                "lmstudio",
                "ollama",
                "gemini",
                "openai",
                "anthropic",
                "groq",
                "together",
                "cloud",
                "noop",
            ],
            "anthropic": [
                "anthropic",
                "openai",
                "gemini",
                "groq",
                "together",
                "ollama",
                "lmstudio",
                "cloud",
                "noop",
            ],
            "auto": [
                "gemini",
                "openai",
                "anthropic",
                "groq",
                "together",
                "ollama",
                "lmstudio",
                "cloud",
                "noop",
            ],
        }

        order = preference_map.get(preferred, preference_map["auto"])

        for name in order:
            try:
                if name == "openai":
                    api_key = self._config.get("openai_api_key", "")
                    model = self._config.get("openai_model", "gpt-4o")
                    prov = provider_registry.get("openai", api_key=api_key, model=model)
                    available = bool(api_key)
                elif name == "gemini":
                    api_key = self._config.get(
                        "gemini_api_key", ""
                    ) or self._config.get("google_api_key", "")
                    model = self._config.get("gemini_model", "gemini-1.5-pro")
                    prov = provider_registry.get("gemini", api_key=api_key, model=model)
                    available = bool(api_key)
                elif name == "ollama":
                    url = self._config.get("ollama_url", "http://localhost:11434")
                    model = self._config.get("ollama_model", "llama3.1")
                    prov = provider_registry.get("ollama", base_url=url, model=model)
                    available = True
                elif name == "cloud":
                    server = self._config.get("server_url", "")
                    key = self._config.get("api_key", "")
                    prov = provider_registry.get(
                        "cloud", server_url=server, api_key=key
                    )
                    available = bool(server and key)
                elif name == "groq":
                    api_key = self._config.get("groq_api_key", "")
                    model = self._config.get("groq_model", "llama3-70b-8192")
                    prov = provider_registry.get("groq", api_key=api_key, model=model)
                    available = bool(api_key)
                elif name == "together":
                    api_key = self._config.get("together_api_key", "")
                    model = self._config.get(
                        "together_model", "mistralai/Mixtral-8x7B-Instruct-v0.1"
                    )
                    prov = provider_registry.get(
                        "together", api_key=api_key, model=model
                    )
                    available = bool(api_key)
                elif name == "lmstudio":
                    url = self._config.get("lmstudio_url", "http://localhost:1234")
                    model = self._config.get("lmstudio_model", "")
                    prov = provider_registry.get("lmstudio", base_url=url, model=model)
                    available = True
                elif name == "anthropic":
                    api_key = self._config.get("anthropic_api_key", "")
                    model = self._config.get(
                        "anthropic_model", "claude-3-opus-20240229"
                    )
                    prov = provider_registry.get(
                        "anthropic", api_key=api_key, model=model
                    )
                    available = bool(api_key)
                else:  # noop or unknown
                    prov = provider_registry.get("noop")
                    available = True

                if not available:
                    continue

                # Attach an availability attribute for backward compatibility
                try:
                    setattr(prov, "available", available)
                except Exception:
                    pass

                self._planner.add_provider(prov)
            except Exception:
                logger.debug(
                    "Failed to instantiate provider adapter: %s", name, exc_info=True
                )

    @property
    def graph(self) -> KnowledgeGraph:
        """Get the live knowledge graph of findings."""
        return self._graph

    @property
    def mode(self) -> ExecutionMode:
        return self._mode

    @property
    def discovered_tools(self) -> list[ToolInfo]:
        return self._discovered_tools

    def _build_context(self) -> dict[str, Any]:
        """Build context dict for the task planner."""
        recent_execs = self._xi_tracker.recent_executions
        last_tool = recent_execs[-1].tool if recent_execs else ""
        prediction_objs = self._xi_predictor.predict_next(
            phase=self._xi_tracker.phase,
            last_tool=last_tool,
            target="",
            findings_count=self._xi_tracker.total_findings,
        )

        # Skill profiler context
        sp = self._get_skill_profiler()
        xi_skill = {
            "level": sp.profile.level,
            "verbosity": sp.profile.verbosity,
            "show_hints": sp.profile.show_hints,
            "score": sp.profile.score,
        }

        # XI core service recommendations
        xi_recs: list[dict[str, str]] = []
        try:
            xics = self._get_xi_core_service()
            from .core.intent_router import IntentRoute
            from .core.session_kernel import SessionContext

            session = SessionContext(session_id="engine", objective="")
            route = IntentRoute(instruction="", mode=self._mode.value)
            xi_recs = [
                {"title": r.title, "reason": r.reason, "priority": r.priority}
                for r in xics.recommend(session, route)
            ]
        except Exception:
            pass

        return {
            "available_tools": [
                {
                    "name": t.name,
                    "binary": t.binary,
                    "capabilities": t.capabilities,
                    "version": t.version,
                }
                for t in self._discovered_tools
            ],
            "mode": self._mode.value,
            "xi_context": self._xi_tracker.summary(),
            "xi_predictions": [
                {"action": p.action, "confidence": p.confidence, "reason": p.reason}
                for p in prediction_objs
            ],
            "xi_skill": xi_skill,
            "xi_recommendations": xi_recs,
        }

    async def plan(self, instruction: str) -> ExecutionPlan:
        """Create an execution plan for the given instruction.

        This is the planning phase — no execution happens here.
        """
        context = self._build_context()
        # Compress context to stay within token limits
        context = self.compress_context(context)
        force_mode = None
        if self._mode == ExecutionMode.REGISTRY:
            force_mode = "static"
        elif self._mode == ExecutionMode.AUTONOMOUS:
            force_mode = "autonomous"

        return await self._planner.plan(instruction, context, force_mode)

    async def execute(
        self,
        instruction: str,
        interactive: bool = True,
        dry_run: bool = False,
        persist: bool = False,
    ) -> EngineResult:
        """Plan and execute a natural language instruction.

        Parameters
        ----------
        instruction:
            The user's natural language command.
        interactive:
            If True, show progress and prompt for unsafe commands.
        dry_run:
            If True, plan only — don't execute.
        """
        start_time = time.monotonic()
        persist_workflow = persist or bool(self._config.get("persist_workflows"))
        store = self._get_offline_store() if persist_workflow else None
        plan_id: str | None = None

        # Check kill switch before execution
        if self._kill_switch.state == KillSwitchState.TRIGGERED:
            logger.warning("Execution aborted: kill switch triggered")
            return EngineResult(
                plan=ExecutionPlan(instruction=instruction, steps=[]),
                mode=self._mode,
                step_results=[],
                total_duration_ms=0.0,
            )

        # Phase 1: Plan
        plan = await self.plan(instruction)

        if interactive:
            self._display_plan(plan)

        if persist_workflow:
            plan_id = str(uuid.uuid4())
            # Narrow type for mypy: ensure store is not None before calling persistence API
            assert store is not None
            store.save_plan(
                plan_id=plan_id,
                instruction=instruction,
                plan_json=json.dumps(plan.to_dict()),
                status="planned",
            )

        # Create session log for this execution
        if self._session_logger is not None:
            log_id = plan_id or str(uuid.uuid4())[:12]
            self._session_logger.create_log(
                session_id=log_id,
                persona=self._config.get("persona", ""),
                llm_provider=self._config.get("model_provider", ""),
                llm_model=self._config.get("gemini_model", ""),
            )
            self._current_log_session_id = log_id
            # Log the input instruction
            self._session_logger.add_command(
                session_id=log_id,
                input_text=instruction,
                ai_plan=[
                    s.command or s.tool or "" for s in plan.steps if s.command or s.tool
                ],
            )

        if dry_run:
            result = EngineResult(plan=plan, mode=self._mode)
            result.plan_id = plan_id
            return result

        if not plan.steps:
            if interactive:
                console.print(
                    "[yellow]Could not create an execution plan from your instruction.[/yellow]\n"
                    "[dim]Tip: Try being more specific, e.g. "
                    "'scan 192.168.1.1 with nmap and nuclei'[/dim]"
                )
            result = EngineResult(plan=plan, mode=self._mode)
            result.plan_id = plan_id
            return result

        # Phase 2: Execute
        self._completed_steps.clear()
        self._replan_attempts = 0
        result = EngineResult(plan=plan, mode=self._mode)
        result.plan_id = plan_id

        if persist_workflow and plan_id:
            assert store is not None
            store.update_plan_status(plan_id, status="running")

        if interactive:
            with Progress(
                SpinnerColumn(),
                TextColumn("[bold cyan]{task.description}"),
                TimeElapsedColumn(),
                console=console,
            ) as progress:
                result = await self._execute_plan(
                    plan, progress, interactive, plan_id, store
                )
        else:
            result = await self._execute_plan(plan, None, interactive, plan_id, store)

        result.plan_id = plan_id

        result.total_duration_ms = (time.monotonic() - start_time) * 1000

        # Record metrics
        metrics = get_metrics()
        total_findings = len(result.all_findings)
        metrics.record_scan(
            duration=result.total_duration_ms / 1000,
            successful=result.success,
            findings_count=total_findings,
        )

        if persist_workflow and plan_id:
            assert store is not None
            store.update_plan_status(
                plan_id,
                status="completed" if result.success else "failed",
                completed=True,
            )

        # Phase 3: Summary
        if interactive:
            self._display_summary(result)

        # Finalize session log
        if self._session_logger is not None and self._current_log_session_id:
            self._session_logger.update_end_time(self._current_log_session_id)
            for sr in result.step_results:
                for f in sr.findings or []:
                    tool = f.get("tool", "unknown")
                    self._session_logger.track_tool_usage(
                        self._current_log_session_id, tool
                    )
            self._current_log_session_id = None

        return result

    async def resume(self, plan_id: str, interactive: bool = True) -> EngineResult:
        """Resume a previously persisted execution plan."""
        store = self._get_offline_store()
        plan_record = store.get_plan(plan_id)
        if not plan_record:
            raise ValueError(f"Plan not found: {plan_id}")

        plan_data = json.loads(plan_record.get("plan_json", "{}"))
        plan = self._plan_from_dict(plan_data)

        # Preload completed steps
        self._completed_steps.clear()
        self._replan_attempts = 0
        for row in plan_record.get("steps", []):
            findings = json.loads(row.get("findings_json") or "[]")
            sr = StepResult(
                step_id=row.get("step_id", ""),
                status=StepStatus(row.get("status", StepStatus.FAILED.value)),
                output=row.get("output", "") or "",
                error=row.get("error", "") or "",
                duration_ms=float(row.get("duration_ms") or 0.0),
                findings=findings,
                retry_count=int(row.get("retry_count") or 0),
                exit_code=row.get("exit_code"),
            )
            self._completed_steps[sr.step_id] = sr

        start_time = time.monotonic()
        store.update_plan_status(plan_id, status="running")
        if interactive:
            with Progress(
                SpinnerColumn(),
                TextColumn("[bold cyan]{task.description}"),
                TimeElapsedColumn(),
                console=console,
            ) as progress:
                result = await self._execute_plan(
                    plan, progress, interactive, plan_id, store
                )
        else:
            result = await self._execute_plan(plan, None, interactive, plan_id, store)
        result.total_duration_ms = (time.monotonic() - start_time) * 1000
        result.plan_id = plan_id

        # Record metrics
        metrics = get_metrics()
        metrics.record_scan(
            duration=result.total_duration_ms / 1000,
            successful=result.success,
            findings_count=len(result.all_findings),
        )

        store.update_plan_status(
            plan_id,
            status="completed" if result.success else "failed",
            completed=True,
        )

        if interactive:
            self._display_summary(result)

        return result

    def _plan_from_dict(self, data: dict[str, Any]) -> ExecutionPlan:
        """Reconstruct an ExecutionPlan from stored JSON data."""
        steps: list[ExecutionStep] = []
        for s in data.get("steps", []):
            step_type_value = s.get("step_type", StepType.TOOL_RUN.value)
            try:
                step_type = StepType(step_type_value)
            except ValueError:
                step_type = StepType.TOOL_RUN
            steps.append(
                ExecutionStep(
                    id=s.get("id", ""),
                    step_type=step_type,
                    tool=s.get("tool"),
                    command=s.get("command"),
                    args=s.get("args", []) or [],
                    target=s.get("target"),
                    depends_on=s.get("depends_on", []) or [],
                    condition=s.get("condition"),
                    timeout=int(s.get("timeout", 300)),
                    description=s.get("description", ""),
                    metadata=s.get("metadata", {}) or {},
                )
            )

        return ExecutionPlan(
            steps=steps,
            source=data.get("source", "registry"),
            confidence=float(data.get("confidence", 0.0)),
            raw_instruction=data.get("raw_instruction", ""),
            interpreted_task=None,
        )

    async def _execute_plan(
        self,
        plan: ExecutionPlan,
        progress: Progress | None,
        interactive: bool,
        plan_id: str | None,
        store: OfflineStore | None,
    ) -> EngineResult:
        """Execute all steps in the plan respecting dependencies.

        Steps with no unmet dependencies are executed in parallel via
        asyncio.gather.  Steps whose dependencies have all completed are
        scheduled in the next wave.  This gives automatic parallelism for
        independent branches while preserving ordering for dependent steps.
        """
        result = EngineResult(plan=plan, mode=self._mode)
        pending = list(plan.steps)

        while pending:
            # Find steps whose dependencies are all satisfied
            ready: list[ExecutionStep] = []
            still_pending: list[ExecutionStep] = []

            for step in pending:
                # Already completed (resume support)
                if step.id in self._completed_steps:
                    sr = self._completed_steps[step.id]
                    result.step_results.append(sr)
                    result.all_findings.extend(sr.findings)
                    result.retries_performed += sr.retry_count
                    continue

                if self._check_dependencies(step):
                    ready.append(step)
                else:
                    still_pending.append(step)

            if not ready:
                # Remaining steps have unmet deps — mark them blocked
                for step in still_pending:
                    sr = StepResult(
                        step_id=step.id,
                        status=StepStatus.BLOCKED,
                        output="Blocked: dependency not met and no more steps can run",
                    )
                    result.step_results.append(sr)
                    self._completed_steps[step.id] = sr
                    self._persist_step(store, plan_id, sr)
                break

            # Execute ready steps — parallel if >1, sequential if 1
            if len(ready) > 1:
                logger.info(
                    "Parallel wave: executing %d steps concurrently: %s",
                    len(ready),
                    [s.id for s in ready],
                )

            async def _run_one(step: ExecutionStep) -> StepResult:
                # Check kill switch
                if self._kill_switch.state == KillSwitchState.TRIGGERED:
                    return StepResult(
                        step_id=step.id,
                        status=StepStatus.SKIPPED,
                        output="Skipped: kill switch triggered",
                    )
                # Check condition
                if step.condition and not self._evaluate_condition(step.condition):
                    sr = StepResult(
                        step_id=step.id,
                        status=StepStatus.SKIPPED,
                        output=f"Skipped: condition not met ({step.condition})",
                    )
                    self._completed_steps[step.id] = sr
                    self._persist_step(store, plan_id, sr)
                    return sr

                task_id = None
                if progress:
                    task_id = progress.add_task(
                        f"[{step.id}] {step.description or step.tool or 'executing'}",
                        total=None,
                    )

                sr = await self._execute_step_with_retry(step, interactive)
                self._completed_steps[step.id] = sr
                self._persist_step(store, plan_id, sr)
                self._record_step_feedback(step, sr)

                # Dynamically mutate the remaining plan steps based on this step's output
                self._adapt_plan_on_step_result(step, sr, plan, still_pending)
                await self._replan_from_feedback(step, sr, plan, still_pending)

                if progress and task_id is not None:
                    status_icon = "✅" if sr.status == StepStatus.SUCCESS else "❌"
                    progress.update(
                        task_id,
                        description=f"{status_icon} [{step.id}] {step.description}",
                        completed=True,
                    )
                return sr

            # Submit to bounded worker pool to control concurrency and cancellation
            tasks = [self._pool.submit(_run_one, s) for s in ready]
            wave_results = await asyncio.gather(*tasks, return_exceptions=True)

            for i, wr in enumerate(wave_results):
                if isinstance(wr, Exception):
                    sr = StepResult(
                        step_id=ready[i].id,
                        status=StepStatus.FAILED,
                        error=str(wr),
                    )
                    self._completed_steps[ready[i].id] = sr
                    self._persist_step(store, plan_id, sr)
                    result.step_results.append(sr)
                elif isinstance(wr, StepResult):
                    result.step_results.append(wr)
                    result.all_findings.extend(wr.findings)
                    result.retries_performed += wr.retry_count

            pending = still_pending

        # Close worker pool before returning (best-effort)
        try:
            await self._pool.close(timeout=5)
        except Exception:
            logger.debug("Error closing sub-agent pool", exc_info=True)
        return result

    def _persist_step(
        self,
        store: OfflineStore | None,
        plan_id: str | None,
        sr: StepResult,
    ) -> None:
        """Helper to persist a step result to the offline store."""
        if store and plan_id:
            store.upsert_step_execution(
                plan_id=plan_id,
                step_id=sr.step_id,
                status=sr.status.value,
                output=sr.output[:5000],
                error=sr.error[:2000],
                findings=sr.findings,
                duration_ms=sr.duration_ms,
                retry_count=sr.retry_count,
                exit_code=sr.exit_code,
            )

    async def _calculate_backoff_delay(self, attempt: int) -> float:
        """Calculate exponential backoff delay with jitter."""
        delay = _RETRY_BASE_DELAY * (_RETRY_BACKOFF_FACTOR**attempt)
        delay = min(delay, _RETRY_MAX_DELAY)  # Cap maximum delay
        # Add jitter (±10%)
        import random

        jitter = delay * random.uniform(0.9, 1.1)
        return jitter

    async def _execute_step_with_retry(
        self, step: ExecutionStep, interactive: bool
    ) -> StepResult:
        """Execute a step with automatic retry on transient failures."""
        retry_count = 0
        last_error = None

        # Don't retry certain step types
        no_retry_types = {StepType.REPORT, StepType.ANALYSIS}
        if step.step_type in no_retry_types:
            return await self._execute_step(step, interactive)

        while retry_count <= _MAX_RETRIES:
            try:
                result = await self._execute_step(step, interactive)

                # Success - return immediately
                if result.status == StepStatus.SUCCESS:
                    result.retry_count = retry_count
                    return result

                # Failure - check if retryable
                if result.status == StepStatus.FAILED and retry_count < _MAX_RETRIES:
                    last_error = result.error
                    # Check if error is transient (retryable)
                    if self._is_transient_error(result.error):
                        retry_count += 1
                        delay = await self._calculate_backoff_delay(retry_count - 1)
                        logger.warning(
                            "Step %s failed (retryable): %s. Retrying in %.1fs (attempt %d/%d)",
                            step.id,
                            result.error,
                            delay,
                            retry_count,
                            _MAX_RETRIES,
                        )
                        await asyncio.sleep(delay)
                        continue

                # Non-retryable or final attempt
                result.retry_count = retry_count
                return result

            except Exception as e:
                last_error = str(e)
                if retry_count < _MAX_RETRIES and self._is_transient_error(last_error):
                    retry_count += 1
                    delay = await self._calculate_backoff_delay(retry_count - 1)
                    logger.warning(
                        "Step %s raised exception (retryable): %s. Retrying in %.1fs (attempt %d/%d)",
                        step.id,
                        str(e),
                        delay,
                        retry_count,
                        _MAX_RETRIES,
                    )
                    await asyncio.sleep(delay)
                    continue
                else:
                    # Non-retryable exception or max retries exceeded
                    return StepResult(
                        step_id=step.id,
                        status=StepStatus.FAILED,
                        error=last_error or str(e),
                        retry_count=retry_count,
                    )

        # Max retries exceeded
        return StepResult(
            step_id=step.id,
            status=StepStatus.FAILED,
            error=f"Max retries ({_MAX_RETRIES}) exceeded: {last_error}",
            retry_count=retry_count,
        )

    def _is_transient_error(self, error: str) -> bool:
        """Check if error is transient and retryable."""
        transient_indicators = [
            "timeout",
            "temporarily unavailable",
            "connection refused",
            "connection reset",
            "connection timeout",
            "temporarily",
            "busy",
            "try again",
            "server is unavailable",
            "gateway timeout",
            "internal server error",
        ]

        error_lower = str(error).lower()
        return any(indicator in error_lower for indicator in transient_indicators)

    async def _execute_step(self, step: ExecutionStep, interactive: bool) -> StepResult:
        """Execute a single step based on its type, routing through engine lifecycle hooks."""
        if step.step_type == StepType.TOOL_RUN:
            return await self._run_tool_step(step, interactive)
        if step.step_type == StepType.SHELL_CMD:
            return await self._run_shell_step(step, interactive)
        # ANALYSIS, REPORT, PARALLEL_GROUP: delegate directly to executor
        return await self._executor.execute_step(step, interactive)

    async def _run_tool_step(
        self, step: ExecutionStep, interactive: bool
    ) -> StepResult:
        """Execute a registered security tool — delegates to ToolExecutor with lifecycle hooks."""
        tool_name = step.tool or ""

        # Check install-and-retry for missing tools
        if tool_name != "__all__":
            resolved = self._resolver.resolve(tool_name, step.args)
            if not resolved.is_safe and any(
                "not found on PATH" in w for w in resolved.warnings
            ):
                installed = await self._try_install_tool(tool_name)
                if installed:
                    self._resolver = DynamicResolver(
                        registered_tools={
                            t.binary: t.path
                            for t in self._discovered_tools
                        }
                        | {t.name: t.path for t in self._discovered_tools}
                    )

        # Permission gate
        original_args_str = " ".join(step.args)
        confirmed_str = await self._apply_permission_gate(
            step, tool_name, original_args_str, interactive
        )
        if confirmed_str == "__forbidden__":
            return StepResult(
                step_id=step.id,
                status=StepStatus.BLOCKED,
                error="Forbidden by permission gate",
            )
        if confirmed_str != original_args_str:
            step = ExecutionStep(
                id=step.id,
                step_type=step.step_type,
                tool=step.tool,
                command=step.command,
                args=confirmed_str.split(),
                target=step.target,
                depends_on=step.depends_on,
                condition=step.condition,
                timeout=step.timeout,
                description=step.description,
                metadata=step.metadata,
            )

        # Delegate core execution to ToolExecutor
        sr = await self._executor.execute_step(step, interactive)

        # Engine-level extras: notifications, learning, session log
        if sr.findings:
            for f in sr.findings:
                notification_center.finding(
                    tool=tool_name,
                    severity=f.get("severity", "info"),
                    description=f.get("description", str(f)),
                    target=step.target or "",
                )
            for f in sr.findings:
                self._graph.ingest_finding(f, tool=tool_name)

        if self._learning_memory is not None and confirmed_str != original_args_str:
            try:
                self._learning_memory.record_with_correction(
                    tools=[tool_name],
                    original=f"{tool_name} {original_args_str}",
                    corrected=confirmed_str,
                    task=step.description or "",
                    findings_after=len(sr.findings),
                    duration_ms=sr.duration_ms,
                    success=sr.status == StepStatus.SUCCESS,
                    target=step.target or "",
                )
            except Exception as exc:
                logger.debug("Failed to record tool correction: %s", exc)

        if self._session_logger is not None and self._current_log_session_id:
            try:
                self._session_logger.add_command(
                    session_id=self._current_log_session_id,
                    input_text=f"{tool_name} {confirmed_str}",
                    execution_time_ms=sr.duration_ms,
                    output_summary=(
                        f"{len(sr.findings)} findings"
                        if sr.findings
                        else f"exit: {sr.exit_code}"
                    ),
                )
                self._session_logger.track_tool_usage(
                    self._current_log_session_id, tool_name
                )
            except Exception as exc:
                logger.debug("Session log recording failed: %s", exc)

        return sr

    async def _run_shell_step(
        self, step: ExecutionStep, interactive: bool
    ) -> StepResult:
        """Execute a shell command — delegate to ToolExecutor with engine-level extras."""
        command = step.command or ""
        if not command:
            return StepResult(
                step_id=step.id,
                status=StepStatus.SKIPPED,
                output="No command specified",
            )

        # Check install for missing base command
        parts = command.split()
        base_cmd = parts[0]
        resolved = self._resolver.resolve(base_cmd, parts[1:] + list(step.args))
        if not resolved.is_safe and any(
            "not found on PATH" in w for w in resolved.warnings
        ):
            installed = await self._try_install_tool(base_cmd)
            if installed:
                self._resolver = DynamicResolver(
                    registered_tools={
                        t.binary: t.path for t in self._discovered_tools
                    }
                    | {t.name: t.path for t in self._discovered_tools}
                )

        # Permission gate
        confirmed_str = await self._apply_permission_gate(
            step, command, command, interactive
        )
        if confirmed_str == "__forbidden__":
            return StepResult(
                step_id=step.id,
                status=StepStatus.BLOCKED,
                error="Forbidden by permission gate",
            )
        if confirmed_str != command:
            step = ExecutionStep(
                id=step.id,
                step_type=step.step_type,
                tool=step.tool,
                command=confirmed_str,
                args=step.args,
                target=step.target,
                depends_on=step.depends_on,
                condition=step.condition,
                timeout=step.timeout,
                description=step.description,
                metadata=step.metadata,
            )

        # Delegate to ToolExecutor
        sr = await self._executor.execute_step(step, interactive)

        # Learning memory
        if self._learning_memory is not None and command != confirmed_str:
            try:
                self._learning_memory.record_with_correction(
                    tools=[base_cmd],
                    original=command,
                    corrected=confirmed_str,
                    task=step.description or "",
                    duration_ms=sr.duration_ms,
                    success=sr.status == StepStatus.SUCCESS,
                    target=step.target or "",
                )
            except Exception as exc:
                logger.debug("Failed to record shell correction: %s", exc)

        # Session log
        if self._session_logger is not None and self._current_log_session_id:
            try:
                self._session_logger.add_command(
                    session_id=self._current_log_session_id,
                    input_text=confirmed_str,
                    execution_time_ms=sr.duration_ms,
                    output_summary=f"exit: {sr.exit_code}",
                )
                self._session_logger.track_tool_usage(
                    self._current_log_session_id, base_cmd
                )
            except Exception as exc:
                logger.debug("Session log recording failed: %s", exc)

        return sr

    async def _apply_permission_gate(
        self,
        step: ExecutionStep,
        value: str,
        display_name: str,
        interactive: bool,
    ) -> str:
        """Check permission gate; return confirmed value, original, or '__forbidden__'."""
        try:
            from .permission_gate import PermissionGate

            gate = PermissionGate()
            gate_result = gate.check(value, tool=step.tool or display_name)
            if gate_result.stage == "forbidden":
                return "__forbidden__"
            if gate_result.requires_review and interactive:
                from .shell_review import review_and_confirm

                confirmed = review_and_confirm(
                    value, step.tool or display_name, gate_result.reason
                )
                if confirmed is None:
                    return "__forbidden__"
                return confirmed
        except Exception as exc:
            logger.debug("Permission gate check failed: %s", exc)
        return value

    def _check_dependencies(self, step: ExecutionStep) -> bool:
        """Check if all dependencies have completed successfully."""
        for dep_id in step.depends_on:
            dep_result = self._completed_steps.get(dep_id)
            if dep_result is None:
                return False
            if dep_result.status not in (StepStatus.SUCCESS, StepStatus.SKIPPED):
                return False
        return True

    def _evaluate_condition(self, condition: str) -> bool:
        """Pillar 3: Step Condition Evaluator.
        Evaluates a step condition dynamically based on completed steps
        and the live KnowledgeGraph state. Supports negations 'not (...)',
        step status checkers, findings checkers, and graph target states.
        """
        condition = condition.strip()

        # 1. Parse negations like not (...)
        if condition.startswith("not ") or condition.startswith("not("):
            if condition.startswith("not "):
                sub = condition[4:].strip()
            else:
                sub = condition[3:].strip()
            if sub.startswith("(") and sub.endswith(")"):
                sub = sub[1:-1].strip()
            return not self._evaluate_condition(sub)

        # 2. Check for step_X.success
        if condition.endswith(".success"):
            step_id = condition[:-8].strip()
            res = self._completed_steps.get(step_id)
            return res is not None and res.status == StepStatus.SUCCESS

        # 3. Check for step_X.failed
        if condition.endswith(".failed"):
            step_id = condition[:-8].strip()
            res = self._completed_steps.get(step_id)
            return res is not None and res.status == StepStatus.FAILED

        # 4. Check for findings count
        if "findings.count > 0" in condition:
            total_findings = sum(
                len(r.findings) for r in self._completed_steps.values()
            )
            return total_findings > 0

        # 5. Check for port_X_open
        port_match = re.match(r"^port_(\d+)_open$", condition)
        if port_match:
            port_num = int(port_match.group(1))
            from siyarix.knowledge_graph import NodeType

            ports = self._graph.find_nodes(NodeType.PORT)
            for p in ports:
                if p.properties.get("port") == port_num:
                    return True
            return False

        # 6. Check for service_Y_running
        service_match = re.match(r"^service_([a-zA-Z0-9_\-]+)_running$", condition)
        if service_match:
            svc_name = service_match.group(1).lower()
            from siyarix.knowledge_graph import NodeType

            services = self._graph.find_nodes(NodeType.SERVICE)
            for s in services:
                if s.label.lower() == svc_name:
                    return True
            return False

        # 7. Check for vulnerability_found
        if condition == "vulnerability_found":
            from siyarix.knowledge_graph import NodeType

            vulns = self._graph.find_nodes(NodeType.VULNERABILITY)
            return len(vulns) > 0

        return True  # Default: execute

    def _record_step_feedback(self, step: ExecutionStep, sr: StepResult) -> None:
        """Feed step outcomes into XI context/predictor and skill profiler."""
        tool_name = step.tool or (
            step.command.split()[0] if step.command else "analysis"
        )
        target = step.target or ""
        self._xi_tracker.record_execution(
            tool=tool_name,
            target=target,
            duration_ms=sr.duration_ms,
            success=sr.status == StepStatus.SUCCESS,
            findings_count=len(sr.findings),
        )
        if step.command:
            self._xi_predictor.learn(step.command)
        elif step.tool:
            cmd = " ".join([step.tool, *step.args, step.target or ""]).strip()
            self._xi_predictor.learn(cmd)
        else:
            cmd = ""

        # Feed into SkillProfiler
        self._get_skill_profiler().record_command(
            command=cmd or "",
            tool=tool_name,
            success=sr.status == StepStatus.SUCCESS,
        )

    async def _replan_from_feedback(
        self,
        step: ExecutionStep,
        sr: StepResult,
        plan: ExecutionPlan,
        still_pending: list[ExecutionStep],
    ) -> None:
        """Trigger planner re-evaluation after failures or zero-finding outcomes."""
        if self._replan_attempts >= self._max_replans:
            return
        if not (
            sr.status == StepStatus.FAILED
            or (sr.status == StepStatus.SUCCESS and len(sr.findings) == 0)
        ):
            return

        trigger = "step_failed" if sr.status == StepStatus.FAILED else "zero_findings"
        replan_ctx = self._build_context()
        replan_ctx.update(
            {
                "trigger_step": step.to_dict(),
                "trigger_result": {
                    "status": sr.status.value,
                    "error": sr.error[:500],
                    "output": sr.output[:1000],
                    "findings_count": len(sr.findings),
                },
                "completed_steps": [
                    s.to_dict() for s in plan.steps if s.id in self._completed_steps
                ],
                "pending_steps": [s.to_dict() for s in still_pending],
            }
        )
        adaptive = await self._planner.replan(
            instruction=plan.raw_instruction or "",
            context=replan_ctx,
            trigger_step=step,
            trigger_reason=trigger,
        )
        if not adaptive or not adaptive.steps:
            return

        existing_ids = {s.id for s in plan.steps} | {s.id for s in still_pending}
        injected: list[ExecutionStep] = []
        for i, candidate in enumerate(adaptive.steps, 1):
            base_id = candidate.id or f"{step.id}_replan_{i}"
            new_id = base_id
            while new_id in existing_ids:
                new_id = f"{base_id}_{i}"
            candidate.id = new_id
            if step.id not in candidate.depends_on:
                candidate.depends_on.append(step.id)
            existing_ids.add(new_id)
            injected.append(candidate)

        if injected:
            still_pending[:0] = injected
            plan.steps.extend(injected)
            self._replan_attempts += 1
            logger.info(
                "Adaptive re-plan injected %d step(s) after %s (%s)",
                len(injected),
                step.id,
                trigger,
            )

    def _adapt_plan_on_step_result(
        self,
        step: ExecutionStep,
        sr: StepResult,
        plan: ExecutionPlan,
        still_pending: list[ExecutionStep],
    ) -> None:
        """Pillar 3: Dynamic Plan Mutator.
        Analyzes the result of a completed step and mutates remaining/pending steps
        to inject retries, fallbacks, or privilege checks at runtime.
        """
        # Heuristic 1: Nmap Host Down / Ping blocked -> Inject -Pn and retry nmap
        if step.tool == "nmap" and (
            "Host seems down" in (sr.error or "")
            or "Host seems down" in (sr.output or "")
            or "try -Pn" in (sr.error or "")
            or "try -Pn" in (sr.output or "")
        ):
            new_args = list(step.args)
            if "-Pn" not in new_args:
                new_args.append("-Pn")
            retry_step = ExecutionStep(
                id=f"{step.id}_retry_pn",
                step_type=StepType.TOOL_RUN,
                tool="nmap",
                args=new_args,
                target=step.target,
                description=f"Retry nmap with -Pn (ping bypass) for {step.target}",
                timeout=step.timeout,
            )
            # Find any steps that depended on the failed step, and update their dependency
            for s in still_pending:
                if step.id in s.depends_on:
                    s.depends_on.remove(step.id)
                    s.depends_on.append(retry_step.id)
            still_pending.insert(0, retry_step)
            logger.info(
                "Dynamic Mutation: Injected nmap -Pn retry step %s", retry_step.id
            )

        # Heuristic 2: Nikto Failure Fallback -> nuclei scan
        elif step.tool == "nikto" and sr.status == StepStatus.FAILED:
            fallback_step = ExecutionStep(
                id=f"{step.id}_fallback_nuclei",
                step_type=StepType.TOOL_RUN,
                tool="nuclei",
                target=step.target,
                description=f"Fallback: nuclei vuln scan against {step.target} after nikto failure",
            )
            for s in still_pending:
                if step.id in s.depends_on:
                    s.depends_on.remove(step.id)
                    s.depends_on.append(fallback_step.id)
            still_pending.insert(0, fallback_step)
            logger.info(
                "Dynamic Mutation: Swapped/added nuclei fallback %s", fallback_step.id
            )

        # Heuristic 3: Gobuster Zero-findings Fallback -> nikto scan
        elif (
            step.tool == "gobuster"
            and sr.status == StepStatus.SUCCESS
            and len(sr.findings) == 0
        ):
            fallback_step = ExecutionStep(
                id=f"{step.id}_fallback_nikto",
                step_type=StepType.TOOL_RUN,
                tool="nikto",
                target=step.target,
                description=f"Zero-findings fallback: nikto scan against {step.target}",
            )
            for s in still_pending:
                if step.id in s.depends_on:
                    s.depends_on.remove(step.id)
                    s.depends_on.append(fallback_step.id)
            still_pending.insert(0, fallback_step)
            logger.info(
                "Dynamic Mutation: Injected nikto fallback %s due to zero gobuster findings",
                fallback_step.id,
            )

        # Heuristic 4: Shell Permission Error -> privilege check
        elif step.step_type == StepType.SHELL_CMD:
            is_permission_denied = False
            err_msg = ((sr.error or "") + (sr.output or "")).lower()
            for indicator in (
                "permission denied",
                "access denied",
                "not allowed",
                "requires elevation",
            ):
                if indicator in err_msg:
                    is_permission_denied = True
                    break

            if is_permission_denied:
                import sys

                priv_cmd = "whoami /priv" if sys.platform == "win32" else "sudo -l"
                priv_step = ExecutionStep(
                    id=f"{step.id}_priv_check",
                    step_type=StepType.SHELL_CMD,
                    command=priv_cmd,
                    description=f"Privilege check due to access denial on step {step.id}",
                )
                still_pending.insert(0, priv_step)
                logger.info(
                    "Dynamic Mutation: Injected privilege check %s after permission error",
                    priv_step.id,
                )

    async def execute_objective(
        self,
        objective: str,
        target: str = "",
        *,
        interactive: bool = False,
    ) -> dict[str, Any]:
        """Execute a high-level objective through the multi-agent coordinator."""
        from .agents.coordinator import CoordinatorAgent

        coordinator = CoordinatorAgent(engine=self)
        return await coordinator.execute_objective(
            objective=objective,
            target=target,
            interactive=interactive,
        )

    # ------------------------------------------------------------------
    # Display helpers
    # ------------------------------------------------------------------

    def _display_plan(self, plan: ExecutionPlan) -> None:
        """Display the execution plan to the user."""
        source_colors = {
            "registry": "blue",
            "autonomous": "green",
            "integrated-registry": "cyan",
            "integrated-autonomous": "magenta",
            "integrated-fallback": "yellow",
        }
        color = source_colors.get(plan.source, "white")

        table = Table(
            title=f"Execution Plan [{plan.source}]",
            show_header=True,
            header_style="bold",
        )
        table.add_column("#", style="dim", width=4)
        table.add_column("Type", style="cyan", width=12)
        table.add_column("Tool/Command", style="bold")
        table.add_column("Target", style="green")
        table.add_column("Description")

        for i, step in enumerate(plan.steps, 1):
            tool_cmd = step.tool or step.command or "—"
            table.add_row(
                str(i),
                step.step_type.value,
                tool_cmd,
                step.target or "—",
                step.description,
            )

        console.print()
        console.print(
            Panel(
                table,
                title=f"[{color}]🚀 Execution Engine — {plan.source.upper()} mode[/{color}]",
                subtitle=f"Confidence: {plan.confidence:.0%}",
            )
        )

        # Chain-of-thought reasoning display
        if plan.reasoning:
            console.print(
                Panel(
                    plan.reasoning[:2000],
                    title="[bold yellow]🧠 Model Reasoning[/bold yellow]",
                    border_style="yellow",
                )
            )
        console.print()

    def compress_context(
        self,
        context: dict[str, Any],
        max_tokens: int = 8000,
    ) -> dict[str, Any]:
        """Compress context window by summarizing verbose fields.
        
        Truncates large tool descriptions, conversation history, and 
        XI context when approaching LLM token limits. Preserves the 
        most recent and highest-priority information.
        """
        compressed = dict(context)

        # Compress available_tools — keep names, truncate descriptions
        tools = compressed.get("available_tools", [])
        if isinstance(tools, list) and len(tools) > 20:
            compressed["available_tools"] = tools[:20]
            compressed["_tools_truncated"] = len(tools) - 20

        # Compress conversation_history — keep last 5 turns only
        history = compressed.get("conversation_history", "")
        if isinstance(history, str) and len(history) > max_tokens:
            lines = history.split("\n")
            compressed["conversation_history"] = "\n".join(lines[-40:])
            compressed["_history_truncated"] = len(lines) - 40

        # Compress xi_context summary
        xi = compressed.get("xi_context", {})
        if isinstance(xi, dict) and xi.get("recent_executions"):
            xi["recent_executions"] = xi["recent_executions"][-10:]
            compressed["xi_context"] = xi

        # Compress xi_recommendations — keep top 5
        recs = compressed.get("xi_recommendations", [])
        if isinstance(recs, list) and len(recs) > 5:
            compressed["xi_recommendations"] = recs[:5]

        return compressed

    def _display_summary(self, result: EngineResult) -> None:
        """Display the execution summary."""
        status_icons = {
            "success": "✅",
            "failed": "❌",
            "skipped": "⏭️",
            "blocked": "🚫",
        }

        console.print()
        lines = [
            f"[bold]Execution Summary[/bold] ({result.mode.value} mode)",
            f"  Duration: {result.total_duration_ms / 1000:.1f}s",
            f"  Steps: {len(result.step_results)}",
        ]

        for status, count in result.summary.items():
            icon = status_icons.get(status, "•")
            lines.append(f"  {icon} {status}: {count}")

        if result.all_findings:
            lines.append(f"  📋 Total findings: {len(result.all_findings)}")

        console.print(
            Panel(
                "\n".join(lines),
                title=(
                    "[bold green]✨ Complete[/bold green]"
                    if result.success
                    else "[bold red]⚠ Issues[/bold red]"
                ),
            )
        )


# ═══════════════════════════════════════════════════════════════════════════
# Agentic Loop has been moved to siyarix.core.agentic_loop
# ═══════════════════════════════════════════════════════════════════════════
