name: "GitHub Actions - Dead Link Checker"
on:
  schedule:
    - cron: '0 12 * * 1' # Every Monday at 12 PM
  pull_request:
    paths:
      - '**/*.md'
      - '**/*.html'

permissions: read-all

jobs:
  lychee:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v4
      - name: Link Checker
        uses: lycheeverse/lychee-action@8646ba30535128ac92d33dfc9133794bfdd9b411 # v2.8.0
        with:
          args: --accept=200,204,429 --no-progress --exclude-path 'wiki-staging/**' --exclude 'https://github.com/siyarix/siyarix/issues' --exclude 'https://github.com/mufthakherul/siyarix/pkgs/container/siyarix' --exclude 'https://github.com/mufthakherul/siyarix/stargazers' './**/*.md' './**/*.html'
          fail: true
