name: "Delete Stale Branches"
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday
  workflow_dispatch:

permissions: read-all

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Delete stale branches
        uses: phntxx/delete-stale-branches@v7 # TODO: pin to SHA
        with:
          githubToken: ${{ secrets.GITHUB_TOKEN }}
          daysBeforeStale: 30
          daysBeforeDelete: 45
          ignoreBranches: "main,develop,production"
