name: "GitHub Actions - Delete Stale Branches"
on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday
  workflow_dispatch:

permissions: read-all

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write
    steps:
      - name: Delete stale branches
        uses: crs-k/stale-branches@138918e25f06d439bf76db5305a591d8a3c03678 # v10.0.0
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          days-before-stale: 30
          days-before-delete: 45
          branches-filter-regex: '^((?!(main|master|stable|develop|production)$).)*$'
